# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Alexander Raistrick

import math
from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

from infinigen2.objects import drawer, handles, table
from infinigen2.objects.door import (
    door_composite_rand,
    door_double_rand,
    door_with_handle,
)
from infinigen2.shaders.functionality_lists import (
    furniture_material_rand,
    glass_material_rand,
)
from infinigen2.util import mesh as mesh_util

__all__ = [
    "StorageParams",
    "StorageResult",
    "cabinet_with_base",
    "cabinet_with_base_rand",
    "cabinet_with_door",
    "cabinet_with_door_rand",
    "storage_cell_shelf",
    "storage_cell_bounds",
    "storage_cell_shelf_rand",
    "storage_composite_rand",
    "storage_dimensions_rand",
    "storage_params_rand",
    "storage_cell_counts",
    "storage_rand",
    "storage_with_legs_rand",
    "storage_bench_rand",
    "storage_side_table_rand",
    "storage_coffee_table_rand",
    "grid_legs_rand",
    "stable_legs_rand",
]


class StorageResult(NamedTuple):
    mesh: pf.MeshObject


class StorageParams(NamedTuple):
    dimensions: pf.Vector
    n_spaces_y: int
    n_spaces_z: int
    material: pf.Material
    frame_thickness: float
    row_divider_width: float
    col_divider_width: float
    back_width: float


@pf.tracer.primitive
def storage_cell_bounds(
    dimensions: pf.Vector,
    n_spaces_y: int,
    n_spaces_z: int,
    frame_thickness: float,
    row_divider_width: float,
    col_divider_width: float,
    back_width: float,
) -> list[tuple[pf.Vector, pf.Vector]]:
    """Interior slot bounds in the shelf's min-corner coordinate system."""
    f, r, c = frame_thickness, row_divider_width, col_divider_width
    y_step = (dimensions.y - 2 * f + c) / n_spaces_y
    z_step = (dimensions.z - 2 * f + r) / n_spaces_z
    slots = []
    for y in range(n_spaces_y):
        y_min = f + y * y_step
        y_max = f + (y + 1) * y_step - c
        for z in range(n_spaces_z):
            z_min = f + z * z_step
            z_max = (
                dimensions.z - f if z == n_spaces_z - 1 else f + (z + 1) * z_step - r
            )
            lower = pf.Vector((back_width, y_min, z_min))
            upper = pf.Vector((dimensions.x, y_max, z_max))
            slots.append((lower, upper))
    return slots


@pf.tracer.primitive
def _storage_drawers_rand(
    rng: pf.RNG,
    slots: list[tuple[pf.Vector, pf.Vector]],
    params: StorageParams,
) -> pf.MeshObject:
    side = min(params.frame_thickness, params.col_divider_width)
    row = min(params.frame_thickness, params.row_divider_width)
    drawers = drawer.drawer_rand(
        rng,
        slots[0][1] - slots[0][0],
        material=params.material,
        frame_widths=(side, side, row, row),
        opening_fraction=0,
    ).mesh
    copies = [drawers.clone() for _ in slots[1:]]
    pf.ops.object.set_transform(drawers, location=slots[0][0])
    for index, copy in enumerate(copies, start=1):
        pf.ops.object.set_transform(copy, location=slots[index][0])
        pf.ops.object.join(drawers, copy)
    return drawers


class _GridWithIndicesResult(NamedTuple):
    mesh: pf.ProcNode[pf.MeshObject]
    index_x: pf.ProcNode[int]
    index_y: pf.ProcNode[int]


@pf.nodes.node_function
def _grid_with_indices(
    vertices_x: t.SocketOrVal[int] = 10,
    vertices_y: t.SocketOrVal[int] = 10,
) -> _GridWithIndicesResult:
    # Code generated by procfunc v0.30.2
    curve_line = pf.nodes.geo.curve_line(end=(1.0, 0.0, 0.0), start=(0, 0, 0))

    resample_curve_count = pf.nodes.geo.resample_curve_count(
        curve=curve_line, count=vertices_x
    )

    spline_parameter = pf.nodes.geo.spline_parameter()

    capture_attribute = pf.nodes.geo.capture_attribute(
        geometry=resample_curve_count,
        factor=spline_parameter.factor,
    )

    input_index = pf.nodes.geo.input_index()

    capture_attribute_1 = pf.nodes.geo.capture_attribute(
        geometry=capture_attribute.geometry,
        index=input_index,
    )

    curve_line_1 = pf.nodes.geo.curve_line(end=(-1.0, 0.0, 0.0), start=(0, 0, 0))

    resample_curve_count_1 = pf.nodes.geo.resample_curve_count(
        curve=curve_line_1, count=vertices_y
    )

    capture_attribute_2 = pf.nodes.geo.capture_attribute(
        geometry=resample_curve_count_1,
        factor=spline_parameter.factor,
    )

    input_index_1 = pf.nodes.geo.input_index()

    capture_attribute_3 = pf.nodes.geo.capture_attribute(
        geometry=capture_attribute_2.geometry,
        index=input_index_1,
    )

    curve_to = pf.nodes.geo.curve_to_mesh(
        curve=capture_attribute_1.geometry,
        profile_curve=capture_attribute_3.geometry,
    )

    return _GridWithIndicesResult(
        curve_to,
        capture_attribute_1.index,
        capture_attribute_3.index,
    )


@pf.nodes.node_function
def _shelf_geometry(
    dimensions: t.SocketOrVal[pf.Vector] = (1.0, 1.0, 1.0),
    n_spaces_y: t.SocketOrVal[int] = 0,
    n_spaces_z: t.SocketOrVal[int] = 0,
    frame_board_dimensions: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    row_divider_width: t.SocketOrVal[float] = 0.0,
    col_divider_width: t.SocketOrVal[float] = 0.0,
    back_width: t.SocketOrVal[float] = 0.05,
) -> pf.ProcNode:
    # Code generated by procfunc v0.30.2
    top_bottom_board_dim = pf.nodes.math.combine_xyz(
        x=dimensions.x, y=dimensions.y, z=frame_board_dimensions.z
    )

    top_board_dimensions = pf.nodes.math.vector_multiply_add(
        a=frame_board_dimensions,
        b=(0.0, -2.0, 0.0),
        addend=top_bottom_board_dim,
    )
    bottom_board_origin = frame_board_dimensions * (0.0, 1.0, 0.0)

    top_board_vertices_y = n_spaces_y.astype(dtype=float) + 1.0

    bottom_board = mesh_util.box(
        size=top_board_dimensions,
        location=bottom_board_origin,
        anchor=(0.0, 0.0, 0.0),
        vertices_y=top_board_vertices_y.astype(dtype=int),
    )
    bottom_board = mesh_util.metric_box_uv(bottom_board)

    # interior clearance above each cell's support surface
    cell_interior_z = pf.nodes.math.multiply_add(
        a=frame_board_dimensions.z, b=-2.0, addend=dimensions.z + row_divider_width
    ) / n_spaces_z.astype(dtype=float)
    cell_clearance = cell_interior_z - row_divider_width

    dim_sub_1frame = dimensions - frame_board_dimensions

    top_board_origin = pf.nodes.math.vector_multiply_add(
        a=dim_sub_1frame,
        b=(0.0, 0.0, 1.0),
        addend=bottom_board_origin,
    )

    top_board = mesh_util.box(
        size=top_board_dimensions,
        location=top_board_origin,
        anchor=(0.0, 0.0, 0.0),
        vertices_y=top_board_vertices_y.astype(dtype=int),
    )
    top_board = mesh_util.metric_box_uv(top_board)
    edge_board_dim_no_margin = pf.nodes.math.combine_xyz(
        x=dimensions.x, y=frame_board_dimensions.y, z=dimensions.z
    )

    edge_board_vertices = pf.nodes.math.vector_ceil(
        edge_board_dim_no_margin / (0.7, 0.7, 0.7)
    ) + (1.0, 1.0, 1.0)
    right_board = mesh_util.box(
        size=edge_board_dim_no_margin,
        location=dim_sub_1frame * (0.0, 1.0, 0.0),
        anchor=(0.0, 0.0, 0.0),
        vertices_x=edge_board_vertices.x.astype(dtype=int),
        vertices_y=edge_board_vertices.y.astype(dtype=int),
        vertices_z=edge_board_vertices.z.astype(dtype=int),
    )
    right_board = mesh_util.metric_box_uv(right_board)

    left_board = mesh_util.box(
        size=edge_board_dim_no_margin,
        anchor=(0.0, 0.0, 0.0),
        vertices_x=edge_board_vertices.x.astype(dtype=int),
        vertices_y=edge_board_vertices.y.astype(dtype=int),
        vertices_z=edge_board_vertices.z.astype(dtype=int),
    )
    left_board = mesh_util.metric_box_uv(left_board)

    join_sides = pf.nodes.geo.join_geometry(
        [bottom_board, top_board, right_board, left_board]
    )

    enable_back_switch = pf.nodes.func.equal(a=back_width, b=0.0, epsilon=0.001)

    dim_sub_2frame = pf.nodes.math.vector_multiply_add(
        a=frame_board_dimensions,
        b=(-2.0, -2.0, -2.0),
        addend=dimensions,
    )

    box_dimensions = pf.nodes.math.vector_multiply_add(
        a=back_width.astype(dtype=pf.Vector),
        b=(1.0, 0.0, 0.0),
        addend=dim_sub_2frame * (0.0, 1.0, 1.0),
    )

    box_result = mesh_util.box(
        size=box_dimensions,
        location=frame_board_dimensions * (0.0, 1.0, 1.0),
        anchor=(0.0, 0.0, 0.0),
    )
    box_result = mesh_util.metric_box_uv(box_result)
    enable_back = pf.nodes.func.switch(switch=enable_back_switch, a=box_result)

    grid_1 = n_spaces_y.astype(dtype=float) + 1.0

    grid_0 = n_spaces_z.astype(dtype=float) + 1.0
    grid_with_indices_result = _grid_with_indices(
        vertices_x=grid_1.astype(dtype=int),
        vertices_y=grid_0.astype(dtype=int),
    )
    transform = pf.nodes.geo.transform(
        geometry=grid_with_indices_result.mesh,
        rotation=(1.570796, 0.0, 1.570796),
    )

    input_position = pf.nodes.geo.input_position()

    offset_forward_avoid_backplate = pf.nodes.math.vector_scale(
        vector=(1.0, 0.0, 0.0), scale=back_width
    )

    bottomleft_interior_point = frame_board_dimensions * (0.0, 1.0, 1.0)

    set_position_position_to_min = pf.nodes.math.vector_multiply_add(
        a=row_divider_width.astype(dtype=pf.Vector),
        b=(0.0, 0.0, -0.5),
        addend=offset_forward_avoid_backplate + bottomleft_interior_point,
    )
    set_position_position_to_min -= pf.nodes.math.combine_xyz(y=col_divider_width * 0.5)

    topright_interior_point = pf.nodes.math.vector_multiply_add(
        a=frame_board_dimensions,
        b=(0.0, -1.0, -1.0),
        addend=dimensions,
    )

    set_position_position_to_max = pf.nodes.math.vector_multiply_add(
        a=row_divider_width.astype(dtype=pf.Vector),
        b=(0.0, 0.0, 0.5),
        addend=topright_interior_point + offset_forward_avoid_backplate,
    )
    set_position_position_to_max += pf.nodes.math.combine_xyz(y=col_divider_width * 0.5)

    set_position_position = pf.nodes.math.map_range(
        value=input_position,
        from_max=(1.0, 1.0, 1.0),
        from_min=(0.0, 0.0, 0.0),
        to_max=set_position_position_to_max,
        to_min=set_position_position_to_min,
    )
    set_position = pf.nodes.geo.set_position(
        geometry=transform, position=set_position_position
    )
    is_left = pf.nodes.func.equal(a=grid_with_indices_result.index_x, b=0)

    is_bottom = pf.nodes.func.equal(a=grid_with_indices_result.index_y, b=0)
    is_top = pf.nodes.func.equal(a=grid_with_indices_result.index_y, b=n_spaces_z)
    instance_b_a = pf.nodes.func.boolean_or(a=is_bottom, b=is_top)

    instance_b_1 = pf.nodes.func.boolean_not(instance_b_a)
    instance_horizontal_boards_selection = pf.nodes.func.boolean_and(
        a=is_left, b=instance_b_1
    )
    vert_board_dimensions_x = dimensions.x - back_width

    hor_board_dims_y = pf.nodes.math.multiply_add(
        a=frame_board_dimensions.y, b=-2.0, addend=dimensions.y
    )

    hor_board_dims = pf.nodes.math.combine_xyz(
        x=vert_board_dimensions_x,
        y=hor_board_dims_y,
        z=row_divider_width,
    )
    box_1 = n_spaces_y.astype(dtype=float) + 1.0

    box_result_1 = mesh_util.box(
        size=hor_board_dims,
        location=pf.nodes.math.combine_xyz(
            y=col_divider_width * 0.5, z=-row_divider_width * 0.5
        ),
        anchor=(0.0, 0.0, 0.0),
        vertices_y=box_1.astype(dtype=int),
    )
    box_result_1 = mesh_util.metric_box_uv(box_result_1)
    instance_horizontal_boards = pf.nodes.geo.instance_on_points(
        points=set_position,
        instance=box_result_1,
        selection=instance_horizontal_boards_selection,
    )

    is_right = pf.nodes.func.equal(a=grid_with_indices_result.index_x, b=n_spaces_y)

    instance_a_a = pf.nodes.func.boolean_or(a=is_left, b=is_right)

    instance_a = pf.nodes.func.boolean_not(instance_a_a)
    instance_b_0 = pf.nodes.func.boolean_not(is_top)
    instance_vertical_boards_selection = pf.nodes.func.boolean_and(
        a=instance_a, b=instance_b_0
    )
    vert_board_dimensions = pf.nodes.math.combine_xyz(
        x=vert_board_dimensions_x,
        y=col_divider_width,
        z=cell_clearance,
    )
    vert_board_origin = pf.nodes.math.vector_multiply_add(
        a=col_divider_width.astype(dtype=pf.Vector),
        b=(0.0, -0.5, 0.0),
        addend=row_divider_width.astype(dtype=pf.Vector) * (0.0, 0.0, 0.5),
    )
    vert_board_vertices = pf.nodes.math.vector_ceil(vert_board_dimensions) + (
        1.0,
        1.0,
        1.0,
    )
    vert_board = mesh_util.box(
        size=vert_board_dimensions,
        location=vert_board_origin,
        anchor=(0.0, 0.0, 0.0),
        vertices_x=vert_board_vertices.x.astype(dtype=int),
        vertices_y=vert_board_vertices.y.astype(dtype=int),
        vertices_z=vert_board_vertices.z.astype(dtype=int),
    )
    vert_board = mesh_util.metric_box_uv(vert_board)
    instance_vertical_boards = pf.nodes.geo.instance_on_points(
        points=set_position,
        instance=vert_board,
        selection=instance_vertical_boards_selection,
    )

    join = pf.nodes.geo.join_geometry(
        [join_sides, enable_back, instance_horizontal_boards, instance_vertical_boards]
    )

    realize_instances = pf.nodes.geo.realize_instances(join)

    return realize_instances


def storage_cell_shelf(
    dimensions: pf.Vector | None = None,
    n_spaces_y: int = 3,
    n_spaces_z: int = 4,
    frame_thickness: float = 0.03,
    row_divider_width: float = 0.025,
    col_divider_width: float = 0.02,
    back_width: float = 0.02,
    frame_material: pf.Material | None = None,
) -> StorageResult:
    if dimensions is None:
        dimensions = pf.Vector((0.35, 1.2, 1.6))
    if frame_material is None:
        frame_material = pf.Material(surface=pf.nodes.shader.principled_bsdf())
    geo = _shelf_geometry(
        dimensions=dimensions,
        n_spaces_y=n_spaces_y,
        n_spaces_z=n_spaces_z,
        frame_board_dimensions=(frame_thickness, frame_thickness, frame_thickness),
        row_divider_width=row_divider_width,
        col_divider_width=col_divider_width,
        back_width=back_width,
    )
    geo = pf.nodes.geo.set_material(geometry=geo, material=frame_material)
    geo = mesh_util.crease_sharp(geo, threshold_degrees=30.0)
    result = pf.nodes.to_mesh_object(geo)
    pf.ops.modifier.bevel(result, width=0.003, segments=2)
    pf.ops.modifier.subdivide_surface(result, levels=2, _skip_apply=True)
    return StorageResult(mesh=result)


@pf.tracer.primitive
def storage_cell_counts(
    dimensions: pf.Vector,
    desired_slot_aspect: float,
    target_cell_height: float,
    frame_thickness: float,
    row_divider_width: float,
    col_divider_width: float,
) -> tuple[int, int]:
    """Fit clear-slot proportions while keeping cells at a usable scale."""
    width = dimensions[1] - 2 * frame_thickness
    height = dimensions[2] - 2 * frame_thickness
    max_y = max(
        1, min(8, int((width + col_divider_width) / (0.18 + col_divider_width)))
    )
    max_z = max(
        1, min(8, int((height + row_divider_width) / (0.10 + row_divider_width)))
    )
    candidates = []
    for ny in range(1, max_y + 1):
        for nz in range(1, max_z + 1):
            clear_width = (width - (ny - 1) * col_divider_width) / ny
            clear_height = (height - (nz - 1) * row_divider_width) / nz
            ratio_error = abs(
                math.log(clear_width / clear_height / desired_slot_aspect)
            )
            size_error = abs(math.log(clear_height / target_cell_height))
            candidates.append((ratio_error + 0.15 * size_error, ny, nz))
    _, ny, nz = min(candidates)
    return ny, nz


def storage_dimensions_rand(rng: pf.RNG) -> pf.Vector:
    """Carcass footprint and height in meters, ordered as depth, width, height."""
    rng_depth, rng_width, rng_height = rng.spawn(3)
    return pf.Vector(
        (
            pf.random.uniform(rng_depth, 0.25, 0.45),
            pf.random.uniform(rng_width, 0.7, 2.5),
            pf.random.clip_gaussian(rng_height, 0.9, 0.4, 0.55, 2.2),
        )
    )


def storage_params_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    material: pf.Material | None = None,
    back_width: float | None = None,
    frame_thickness: float | None = None,
    row_divider_width: float | None = None,
    col_divider_width: float | None = None,
    desired_slot_aspect: float | None = None,
) -> StorageParams:
    """Resolve every carcass parameter the caller left unspecified."""
    (
        rng_size,
        rng_frame,
        rng_row,
        rng_col,
        rng_aspect,
        rng_cell,
        rng_back,
        rng_mat,
    ) = rng.spawn(8)
    if dimensions is None:
        dimensions = storage_dimensions_rand(rng_size)
    if frame_thickness is None:
        upper = min(0.06, min(dimensions[1], dimensions[2]) * 0.25)
        frame_thickness = pf.random.uniform(rng_frame, min(0.02, upper * 0.5), upper)
    rows = 1 if n_spaces_z is None else n_spaces_z
    cols = 1 if n_spaces_y is None else n_spaces_y
    if row_divider_width is None:
        upper = min(0.05, (dimensions[2] - 2 * frame_thickness) / rows * 0.25)
        row_divider_width = pf.random.uniform(rng_row, min(0.015, upper * 0.5), upper)
    if col_divider_width is None:
        upper = min(0.04, (dimensions[1] - 2 * frame_thickness) / cols * 0.25)
        col_divider_width = pf.random.uniform(rng_col, min(0.01, upper * 0.5), upper)
    if desired_slot_aspect is None:
        desired_slot_aspect = pf.random.uniform(rng_aspect, 2 / 3, 4.0)
    fitted = storage_cell_counts(
        dimensions,
        desired_slot_aspect,
        pf.random.uniform(rng_cell, 0.20, 0.40),
        frame_thickness,
        row_divider_width,
        col_divider_width,
    )
    if back_width is None:
        rng_choice, rng_depth = rng_back.spawn(2)
        upper = min(0.04, dimensions[0] * 0.25)
        back_width = pf.control.choice(
            rng_choice,
            [
                (0.0, 0.5),
                (pf.random.uniform(rng_depth, min(0.01, upper * 0.5), upper), 0.5),
            ],
        )
    if material is None:
        material = furniture_material_rand(rng_mat, pf.nodes.shader.coord().uv)
    return StorageParams(
        dimensions,
        fitted[0] if n_spaces_y is None else n_spaces_y,
        fitted[1] if n_spaces_z is None else n_spaces_z,
        material,
        frame_thickness,
        row_divider_width,
        col_divider_width,
        back_width,
    )


def storage_cell_shelf_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    frame_material: pf.Material | None = None,
    back_width: float | None = None,
    frame_thickness: float | None = None,
    row_divider_width: float | None = None,
    col_divider_width: float | None = None,
    desired_slot_aspect: float | None = None,
) -> StorageResult:
    """Open cell shelf; storage_composite_rand adds sampled drawer or door fronts."""
    rng_params, rng_bevel = rng.spawn(2)
    params = storage_params_rand(
        rng_params,
        dimensions,
        n_spaces_y,
        n_spaces_z,
        frame_material,
        back_width,
        frame_thickness,
        row_divider_width,
        col_divider_width,
        desired_slot_aspect,
    )
    board = params.frame_thickness
    geo = _shelf_geometry(
        dimensions=params.dimensions,
        n_spaces_y=params.n_spaces_y,
        n_spaces_z=params.n_spaces_z,
        frame_board_dimensions=(board, board, board),
        row_divider_width=params.row_divider_width,
        col_divider_width=params.col_divider_width,
        back_width=params.back_width,
    )
    geo = pf.nodes.geo.set_material(geometry=geo, material=params.material)
    geo = mesh_util.crease_sharp(geo, threshold_degrees=30.0)
    result = pf.nodes.to_mesh_object(geo)
    pf.ops.modifier.bevel(
        result, width=pf.random.uniform(rng_bevel, 0.001, 0.005), segments=2
    )
    # left unapplied so fronts and legs joined in afterwards share this density
    pf.ops.modifier.subdivide_surface(result, levels=2, _skip_apply=True)
    return StorageResult(mesh=result)


def _storage_doors_rand(
    rng: pf.RNG, dimensions: pf.Vector, material: pf.Material
) -> pf.MeshObject:
    rng_door_choice, rng_door, rng_style, rng_handle = rng.spawn(4)

    def bar_pull(r: pf.RNG) -> handles.HandleResult:
        return handles.bar_pull_handle_rand(
            r, grip_length=min(0.06, dimensions.z * 0.5)
        )

    handle_fn = pf.control.choice(
        rng_style, [(bar_pull, 1.0), (handles.knob_handle_rand, 1.0)]
    )
    door_fn = pf.control.choice(
        rng_door_choice, [(door_composite_rand, 2.0), (door_double_rand, 1.0)]
    )
    return door_fn(
        rng_door,
        dimensions=dimensions,
        material=material,
        handle=handle_fn(rng_handle).mesh,
    ).mesh


def storage_composite_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    frame_material: pf.Material | None = None,
    back_width: float | None = None,
    frame_thickness: float | None = None,
    row_divider_width: float | None = None,
    col_divider_width: float | None = None,
    desired_slot_aspect: float | None = None,
) -> StorageResult:
    """Sample one open, drawer, single-door or double-door cabinet treatment.

    The requested depth always reserves a front slab, so every treatment stays
    inside the footprint callers place and collide against.
    """
    rng_params, rng_shelf, rng_choice, rng_front = rng.spawn(4)
    params = storage_params_rand(
        rng_params,
        dimensions,
        n_spaces_y,
        n_spaces_z,
        frame_material,
        back_width,
        frame_thickness,
        row_divider_width,
        col_divider_width,
        desired_slot_aspect,
    )
    front_thickness = min(0.018, params.dimensions.x * 0.1)
    carcass_depth = params.dimensions.x - front_thickness
    carcass = storage_cell_shelf_rand(
        rng_shelf,
        pf.Vector((carcass_depth, params.dimensions.y, params.dimensions.z)),
        params.n_spaces_y,
        params.n_spaces_z,
        params.material,
        params.back_width,
        params.frame_thickness,
        params.row_divider_width,
        params.col_divider_width,
    ).mesh
    slots = storage_cell_bounds(
        pf.Vector((carcass_depth, params.dimensions.y, params.dimensions.z)),
        params.n_spaces_y,
        params.n_spaces_z,
        params.frame_thickness,
        params.row_divider_width,
        params.col_divider_width,
        params.back_width,
    )

    def open_front(_r: pf.RNG) -> pf.MeshObject | None:
        return None

    def drawer_front(r: pf.RNG) -> pf.MeshObject | None:
        return _storage_drawers_rand(r, slots, params)

    def door_front(r: pf.RNG) -> pf.MeshObject | None:
        front = _storage_doors_rand(
            r,
            pf.Vector((front_thickness, params.dimensions.y, params.dimensions.z)),
            params.material,
        )
        pf.ops.object.set_transform(front, location=(carcass_depth, 0, 0))
        return front

    front_fn = pf.control.choice(
        rng_choice,
        [(open_front, 1.0), (drawer_front, 3.0), (door_front, 2.0)],
    )
    front = front_fn(rng_front)
    if front is not None:
        pf.ops.object.join(carcass, front)
    return StorageResult(mesh=carcass)


def cabinet_with_base(
    dimensions: pf.Vector | None = None,
    base_height: float = 0.0762,
    leg_diameter: float = 0.0762,
    frame_material: pf.Material | None = None,
) -> StorageResult:
    """Cabinet carcass raised on a leg base occupying the bottom base_height of
    the overall height."""
    if dimensions is None:
        dimensions = pf.Vector((0.3, 0.5, 1.2))
    if frame_material is None:
        frame_material = pf.Material(surface=pf.nodes.shader.principled_bsdf())
    carcass = storage_cell_shelf(
        dimensions=pf.Vector((dimensions.x, dimensions.y, dimensions.z - base_height)),
        frame_material=frame_material,
    ).mesh
    pf.ops.object.set_transform(carcass, location=(0.0, 0.0, base_height))
    base = table.base_square(
        dimensions=pf.Vector((dimensions.y, dimensions.x, base_height)),
        leg_diameter=leg_diameter,
    ).mesh
    pf.ops.object.set_material(
        base, surface=frame_material.surface, displacement=frame_material.displacement
    )
    # bases separate their frames along local x, so turn that across the width
    pf.ops.object.set_transform(
        base,
        location=(dimensions.x * 0.5, dimensions.y * 0.5, 0.0),
        rotation_euler=(0.0, 0.0, math.pi / 2),
    )
    pf.ops.object.join(carcass, base)
    return StorageResult(mesh=carcass)


def cabinet_with_base_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    rng, rng_shelves, rng_mat, rng_base_sel, rng_base = rng.spawn(5)
    if dimensions is None:
        depth = pf.random.uniform(rng, 0.25, 0.35)
        width = pf.random.uniform(rng, 0.3, 0.55)
        height = pf.random.uniform(rng, 0.9, 1.8)
        dimensions = pf.Vector((depth, width, height))
    frame_material = furniture_material_rand(rng_mat, pf.nodes.shader.coord().uv)
    base_height = pf.random.uniform(rng, 0.0254, 0.1524)
    leg_diameter = pf.random.uniform(rng, 0.0508, 0.127)

    carcass = storage_cell_shelf_rand(
        rng_shelves,
        dimensions=pf.Vector((dimensions.x, dimensions.y, dimensions.z - base_height)),
        frame_material=frame_material,
    ).mesh
    pf.ops.object.set_transform(carcass, location=(0.0, 0.0, base_height))
    base_fn = pf.control.choice(
        rng_base_sel, [(table.base_square_rand, 1.0), (table.base_straight_rand, 1.0)]
    )
    base = base_fn(
        rng_base,
        dimensions=pf.Vector((dimensions.y, dimensions.x, base_height)),
        material=frame_material,
        leg_diameter=leg_diameter,
        leg_placement_bottom_scale=1.0,
    ).mesh
    # bases separate their frames along local x, so turn that across the width
    pf.ops.object.set_transform(
        base,
        location=(dimensions.x * 0.5, dimensions.y * 0.5, 0.0),
        rotation_euler=(0.0, 0.0, math.pi / 2),
    )
    pf.ops.object.join(carcass, base)
    return StorageResult(mesh=carcass)


@pf.nodes.node_function
def _grid_legs(
    depth: t.SocketOrVal[float],
    width: t.SocketOrVal[float],
    height: t.SocketOrVal[float],
    margin_frac: t.SocketOrVal[float],
    spacing_frac: t.SocketOrVal[float],
    diameter: t.SocketOrVal[float],
) -> pf.ProcNode:
    margin_x = depth * margin_frac
    margin_y = width * margin_frac
    n_x = pf.nodes.math.clamp(
        pf.nodes.math.floor((depth - 2.0 * margin_x) / spacing_frac) + 1.0,
        2.0,
        5.0,
    ).astype(dtype=int)
    n_y = pf.nodes.math.clamp(
        pf.nodes.math.floor((width - 2.0 * margin_y) / spacing_frac) + 1.0,
        2.0,
        5.0,
    ).astype(dtype=int)
    span_x = depth - 2.0 * margin_x - diameter
    span_y = width - 2.0 * margin_y - diameter
    grid = pf.nodes.geo.mesh_grid(
        size_x=span_x,
        size_y=span_y,
        vertices_x=n_x,
        vertices_y=n_y,
    )
    position = pf.nodes.geo.input_position()
    interior_x = pf.nodes.func.less_than(
        a=pf.nodes.math.absolute(position.x), b=span_x * 0.5 - 1e-4
    )
    interior_y = pf.nodes.func.less_than(
        a=pf.nodes.math.absolute(position.y), b=span_y * 0.5 - 1e-4
    )
    interior = pf.nodes.func.boolean_and(a=interior_x, b=interior_y)
    boundary = pf.nodes.geo.delete_geometry(
        geometry=grid.mesh, selection=interior, domain="POINT"
    )
    points = pf.nodes.geo.transform(
        boundary,
        translation=pf.nodes.math.combine_xyz(
            x=depth * 0.5 - diameter * 0.5,
            y=width * 0.5 - diameter * 0.5,
        ),
    )
    leg = mesh_util.box(
        size=pf.nodes.math.combine_xyz(x=diameter, y=diameter, z=height),
        anchor=(0.0, 0.0, 0.0),
    )
    leg = mesh_util.metric_box_uv(leg)
    return pf.nodes.geo.realize_instances(
        pf.nodes.geo.instance_on_points(points=points, instance=leg)
    )


def grid_legs_rand(
    rng: pf.RNG,
    dimensions: pf.Vector,
    leg_height: t.SocketOrVal[float],
    close_edges: bool = False,
    diameter: float | None = None,
) -> pf.MeshObject:
    rngs = rng.spawn(3)
    rng_margin = rngs[0]
    rng_spacing = rngs[1]
    rng_diameter = rngs[2]
    depth = dimensions[0]
    width = dimensions[1]
    if close_edges:
        margin_frac = pf.random.uniform(rng_margin, 0.04, 0.08)
    else:
        margin_frac = pf.random.uniform(rng_margin, 0.08, 0.16)
    max_spacing = pf.nodes.math.maximum(depth, width) * 0.55
    spacing_frac = pf.random.clip_gaussian(rng_spacing, 0.5, 0.3, 0.25, max_spacing)
    if diameter is None:
        diameter = pf.random.uniform(rng_diameter, 0.025, 0.14)
    geo = _grid_legs(depth, width, leg_height, margin_frac, spacing_frac, diameter)
    geo = mesh_util.crease_sharp(geo, threshold_degrees=30.0)
    return pf.nodes.to_mesh_object(geo)


def _table_base_rand(
    rng: pf.RNG,
    dimensions: pf.Vector,
    leg_height: t.SocketOrVal[float],
    close_edges: bool = False,
) -> pf.MeshObject:
    # keep-local: table imports storage for coffee-table composition.
    from infinigen2.objects import table

    rng_choice, rng_base = rng.spawn(2)
    depth = dimensions[0]
    width = dimensions[1]
    base_fn = pf.control.choice(
        rng_choice,
        [(table.base_straight_rand, 1.0), (table.base_square_rand, 1.0)],
    )
    base_result = base_fn(
        rng_base,
        dimensions=(depth * 0.96, width * 0.96, leg_height),
        close_edges=close_edges,
    )
    base_min = pf.ops.attr.bbox_min_max(base_result.mesh, global_coords=False)[0]
    pf.ops.object.set_transform(
        base_result.mesh,
        location=(depth * 0.5, width * 0.5, base_min[2] * -1.0),
    )
    return base_result.mesh


def stable_legs_rand(
    rng: pf.RNG,
    dimensions: pf.Vector,
    leg_height: t.SocketOrVal[float],
    close_edges: bool = False,
) -> pf.MeshObject:
    rng_choice, rng_base = rng.spawn(2)
    fn = pf.control.choice(
        rng_choice,
        [(grid_legs_rand, 0.4), (_table_base_rand, 0.6)],
    )
    return fn(rng_base, dimensions, leg_height, close_edges=close_edges)


def storage_with_legs_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    frame_material: pf.Material | None = None,
    back_width: float | None = None,
    leg_height: float | None = None,
    close_edges: bool = False,
    desired_slot_aspect: float | None = None,
) -> StorageResult:
    """Cell shelf raised on a stable compositional base."""
    rng, rng_body, rng_legs = rng.spawn(3)
    if dimensions is None:
        dimensions = storage_dimensions_rand(rng)
    if leg_height is None:
        leg_height = pf.random.uniform(rng, 0.15, 0.3)
    body_dimensions = pf.Vector(
        (dimensions[0], dimensions[1], dimensions[2] - leg_height)
    )
    body_result = storage_composite_rand(
        rng_body,
        dimensions=body_dimensions,
        n_spaces_y=n_spaces_y,
        n_spaces_z=n_spaces_z,
        frame_material=frame_material,
        back_width=back_width,
        desired_slot_aspect=desired_slot_aspect,
    )
    pf.ops.mesh.transform(body_result.mesh, location=(0.0, 0.0, leg_height))
    legs = stable_legs_rand(rng_legs, dimensions, leg_height, close_edges=close_edges)
    pf.ops.object.join(body_result.mesh, legs)
    return StorageResult(mesh=body_result.mesh)


def storage_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    frame_material: pf.Material | None = None,
    back_width: float | None = None,
    desired_slot_aspect: float | None = None,
) -> StorageResult:
    """Cell shelf, half of them raised on a stable compositional base."""
    rng, rng_choice, rng_storage = rng.spawn(3)
    if dimensions is None:
        dimensions = storage_dimensions_rand(rng)
    storage_func = pf.control.choice(
        rng_choice,
        [(storage_composite_rand, 1.0), (storage_with_legs_rand, 1.0)],
    )
    return storage_func(
        rng_storage,
        dimensions=dimensions,
        n_spaces_y=n_spaces_y,
        n_spaces_z=n_spaces_z,
        frame_material=frame_material,
        back_width=back_width,
        desired_slot_aspect=desired_slot_aspect,
    )


def storage_bench_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
) -> StorageResult:
    """Outward-facing storage bench at dining-seat height."""
    if dimensions is None:
        dimensions = pf.Vector(
            (
                pf.random.uniform(rng, 0.38, 0.48),
                pf.random.uniform(rng, 0.9, 2.5),
                pf.random.uniform(rng, 0.42, 0.5),
            )
        )
    return storage_with_legs_rand(
        rng,
        dimensions=dimensions,
        n_spaces_z=1,
        leg_height=dimensions[2] * pf.random.uniform(rng, 0.15, 0.35),
        close_edges=True,
    )


def storage_coffee_table_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    """Coffee table whose body is a cell shelf."""
    # keep-local: table imports storage for coffee-table composition.
    from infinigen2.objects import table

    rng_dimensions, rng_leg_height, rng_storage = rng.spawn(3)
    if dimensions is None:
        dimensions = pf.Vector(table.coffee_table_dimensions_rand(rng_dimensions))
    return storage_with_legs_rand(
        rng_storage,
        dimensions=dimensions,
        n_spaces_z=1,
        leg_height=dimensions[2] * pf.random.uniform(rng_leg_height, 0.3, 0.7),
    )


def storage_side_table_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    """Side table whose body is a cell shelf."""
    # keep-local: table imports storage for coffee-table composition.
    from infinigen2.objects import table

    if dimensions is None:
        dimensions = pf.Vector(table.side_table_dimensions_rand(rng))
    result = storage_with_legs_rand(
        rng,
        dimensions=dimensions,
        n_spaces_z=1,
        leg_height=dimensions[2] * pf.random.uniform(rng, 0.25, 0.55),
    )
    mesh_util.center_footprint(result.mesh)
    return result


def cabinet_with_door(
    dimensions: pf.Vector | None = None,
    frame_material: pf.Material | None = None,
) -> StorageResult:
    if dimensions is None:
        dimensions = pf.Vector((0.3, 0.5, 1.2))
    if frame_material is None:
        frame_material = pf.Material(surface=pf.nodes.shader.principled_bsdf())
    thickness = 0.019
    shelf_dimensions = pf.Vector((dimensions.x - thickness, dimensions.y, dimensions.z))
    carcass_result = storage_cell_shelf(
        dimensions=shelf_dimensions, frame_material=frame_material
    )
    door_result = door_with_handle(
        dimensions=pf.Vector((thickness, dimensions.y, dimensions.z)),
        material=frame_material,
    )
    pf.ops.object.set_transform(
        door_result.mesh, location=(dimensions.x - thickness, 0.0, 0.0)
    )
    pf.ops.object.join(carcass_result.mesh, door_result.mesh)
    return StorageResult(mesh=carcass_result.mesh)


def cabinet_with_door_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    rng, rng_shelves, rng_front, rng_mat, rng_front_mat, rng_handle = rng.spawn(6)
    if dimensions is None:
        depth = pf.random.uniform(rng, 0.25, 0.35)
        # cap width to v1's single-door range so one door stays a realistic panel
        width = pf.random.uniform(rng, 0.3, 0.55)
        height = pf.random.uniform(rng, 0.9, 1.8)
        dimensions = pf.Vector((depth, width, height))
    vec = pf.nodes.shader.coord().uv
    frame_material = furniture_material_rand(rng_mat, vec)

    (
        rng_front_choice,
        rng_front_body,
        rng_inner_choice,
        rng_inner_body,
    ) = rng_front_mat.spawn(4)
    front_material = pf.control.choice(
        rng_front_choice,
        [
            (lambda _rng: frame_material, 2.0),
            (lambda r: furniture_material_rand(r, vec), 1.0),
        ],
    )(rng_front_body)

    inner_material = pf.control.choice(
        rng_inner_choice,
        [
            (lambda r: glass_material_rand(r, vec), 0.4),
            (lambda _rng: front_material, 0.6),
        ],
    )(rng_inner_body)

    thickness = pf.random.uniform(rng, 0.016, 0.022)
    shelf_dimensions = pf.Vector((dimensions.x - thickness, dimensions.y, dimensions.z))
    carcass_result = storage_cell_shelf_rand(
        rng_shelves,
        dimensions=shelf_dimensions,
        frame_material=frame_material,
    )
    rng_handle, rng_handle_choice = rng_handle.spawn(2)
    handle_func = pf.control.choice(
        rng_handle_choice,
        [
            (handles.bar_pull_handle_rand, 6.0),
            (handles.curved_pull_handle_rand, 4.0),
            (handles.knob_handle_rand, 2.0),
            (handles.lever_handle_rand, 1.0),
        ],
    )
    rng_front, rng_front_choice = rng_front.spawn(2)
    front_func = pf.control.choice(
        rng_front_choice, [(door_composite_rand, 2.0), (door_double_rand, 1.0)]
    )
    door_result = front_func(
        rng_front,
        dimensions=pf.Vector((thickness, dimensions.y, dimensions.z)),
        material=front_material,
        inner_material=inner_material,
        handle=handle_func(rng_handle).mesh,
    )
    pf.ops.object.set_transform(
        door_result.mesh, location=(dimensions.x - thickness, 0.0, 0.0)
    )
    pf.ops.object.join(carcass_result.mesh, door_result.mesh)
    return StorageResult(mesh=carcass_result.mesh)
