# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Alexander Raistrick

import math
from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

from infinigen2.objects import handles, table
from infinigen2.objects.door import (
    door_composite_rand,
    door_with_handle,
)
from infinigen2.shaders.functionality_lists import (
    furniture_material_rand,
    glass_material_rand,
)
from infinigen2.util.mesh import center_footprint, crease_sharp, metric_box_uv

__all__ = [
    "StorageResult",
    "cabinet_with_base",
    "cabinet_with_base_rand",
    "cabinet_with_door",
    "cabinet_with_door_rand",
    "storage_cell_shelf",
    "storage_cell_shelf_rand",
    "storage_dimensions_and_cell_counts_rand",
    "storage_rand",
    "storage_with_legs_rand",
    "storage_bench_rand",
    "storage_side_table_rand",
    "storage_coffee_table_rand",
    "grid_legs_rand",
    "stable_legs_rand",
]


class StorageResult(NamedTuple):
    mesh: pf.MeshObject


def _back_width_rand(rng: pf.RNG) -> float:
    return pf.control.choice(
        rng,
        [
            (0.0, 1.0),
            (pf.random.uniform(rng, 0.01, 0.04), 1.0),
        ],
    )


@pf.nodes.node_function
def _box(
    dimensions: t.SocketOrVal[pf.Vector] = (0.39, 0.335, 0.02),
    origin: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    vertices_x: t.SocketOrVal[int] = 2,
    vertices_y: t.SocketOrVal[int] = 2,
    vertices_z: t.SocketOrVal[int] = 2,
) -> pf.ProcNode:
    # Code generated by procfunc v0.30.2
    cube = pf.nodes.geo.mesh_cube(
        vertices_x=vertices_x,
        vertices_y=vertices_y,
        vertices_z=vertices_z,
    )

    input_position = pf.nodes.geo.input_position()

    set_position_position = pf.nodes.math.map_range(
        value=input_position,
        from_max=(0.5, 0.5, 0.5),
        from_min=(-0.5, -0.5, -0.5),
        to_max=origin + dimensions,
        to_min=origin,
    )

    set_position = pf.nodes.geo.set_position(
        geometry=cube.mesh, position=set_position_position
    )

    return metric_box_uv(set_position)


@pf.nodes.node_function
def _box_even(
    dimensions: t.SocketOrVal[pf.Vector] = (0.39, 0.335, 0.02),
    origin: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    face_size_approx: t.SocketOrVal[pf.Vector] = (1.0, 1.0, 1.0),
) -> pf.ProcNode:
    # Code generated by procfunc v0.30.2
    box_vertices_x_a = pf.nodes.math.vector_ceil(dimensions / face_size_approx)

    box_vertices_x = box_vertices_x_a + (1.0, 1.0, 1.0)
    box_result = _box(
        dimensions=dimensions,
        origin=origin,
        vertices_x=box_vertices_x.x.astype(dtype=int),
        vertices_y=box_vertices_x.y.astype(dtype=int),
        vertices_z=box_vertices_x.z.astype(dtype=int),
    )
    return box_result


class _GridWithIndicesResult(NamedTuple):
    mesh: pf.ProcNode[pf.MeshObject]
    index_x: pf.ProcNode[int]
    index_y: pf.ProcNode[int]


@pf.nodes.node_function
def _grid_with_indices(
    vertices_x: t.SocketOrVal[int] = 10,
    vertices_y: t.SocketOrVal[int] = 10,
) -> _GridWithIndicesResult:
    # Code generated by procfunc v0.30.2
    curve_line = pf.nodes.geo.curve_line(end=(1.0, 0.0, 0.0), start=(0, 0, 0))

    resample_curve_count = pf.nodes.geo.resample_curve_count(
        curve=curve_line, count=vertices_x
    )

    spline_parameter = pf.nodes.geo.spline_parameter()

    capture_attribute = pf.nodes.geo.capture_attribute(
        geometry=resample_curve_count,
        factor=spline_parameter.factor,
    )

    input_index = pf.nodes.geo.input_index()

    capture_attribute_1 = pf.nodes.geo.capture_attribute(
        geometry=capture_attribute.geometry,
        index=input_index,
    )

    curve_line_1 = pf.nodes.geo.curve_line(end=(-1.0, 0.0, 0.0), start=(0, 0, 0))

    resample_curve_count_1 = pf.nodes.geo.resample_curve_count(
        curve=curve_line_1, count=vertices_y
    )

    capture_attribute_2 = pf.nodes.geo.capture_attribute(
        geometry=resample_curve_count_1,
        factor=spline_parameter.factor,
    )

    input_index_1 = pf.nodes.geo.input_index()

    capture_attribute_3 = pf.nodes.geo.capture_attribute(
        geometry=capture_attribute_2.geometry,
        index=input_index_1,
    )

    curve_to = pf.nodes.geo.curve_to_mesh(
        curve=capture_attribute_1.geometry,
        profile_curve=capture_attribute_3.geometry,
    )

    return _GridWithIndicesResult(
        curve_to,
        capture_attribute_1.index,
        capture_attribute_3.index,
    )


@pf.nodes.node_function
def _shelf_geometry(
    dimensions: t.SocketOrVal[pf.Vector] = (1.0, 1.0, 1.0),
    n_spaces_y: t.SocketOrVal[int] = 0,
    n_spaces_z: t.SocketOrVal[int] = 0,
    frame_board_dimensions: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    row_divider_width: t.SocketOrVal[float] = 0.0,
    col_divider_width: t.SocketOrVal[float] = 0.0,
    back_width: t.SocketOrVal[float] = 0.05,
) -> pf.ProcNode:
    # Code generated by procfunc v0.30.2
    top_bottom_board_dim = pf.nodes.math.combine_xyz(
        x=dimensions.x, y=dimensions.y, z=frame_board_dimensions.z
    )

    top_board_dimensions = pf.nodes.math.vector_multiply_add(
        a=frame_board_dimensions,
        b=(0.0, -2.0, 0.0),
        addend=top_bottom_board_dim,
    )
    bottom_board_origin = frame_board_dimensions * (0.0, 1.0, 0.0)

    top_board_vertices_y = n_spaces_y.astype(dtype=float) + 1.0

    bottom_board = _box(
        dimensions=top_board_dimensions,
        origin=bottom_board_origin,
        vertices_y=top_board_vertices_y.astype(dtype=int),
    )

    # interior clearance above each cell's support surface
    cell_interior_z = pf.nodes.math.multiply_add(
        a=frame_board_dimensions.z, b=-1.0, addend=dimensions.z
    ) / n_spaces_z.astype(dtype=float)
    cell_clearance = cell_interior_z - row_divider_width

    dim_sub_1frame = dimensions - frame_board_dimensions

    top_board_origin = pf.nodes.math.vector_multiply_add(
        a=dim_sub_1frame,
        b=(0.0, 0.0, 1.0),
        addend=bottom_board_origin,
    )

    top_board = _box(
        dimensions=top_board_dimensions,
        origin=top_board_origin,
        vertices_y=top_board_vertices_y.astype(dtype=int),
    )
    edge_board_dim_no_margin = pf.nodes.math.combine_xyz(
        x=dimensions.x, y=frame_board_dimensions.y, z=dimensions.z
    )

    right_board = _box_even(
        dimensions=edge_board_dim_no_margin,
        origin=dim_sub_1frame * (0.0, 1.0, 0.0),
        face_size_approx=(0.7, 0.7, 0.7),
    )

    left_board = _box_even(
        dimensions=edge_board_dim_no_margin, face_size_approx=(0.7, 0.7, 0.7)
    )

    join_sides = pf.nodes.geo.join_geometry(
        [bottom_board, top_board, right_board, left_board]
    )

    enable_back_switch = pf.nodes.func.equal(a=back_width, b=0.0, epsilon=0.001)

    dim_sub_2frame = pf.nodes.math.vector_multiply_add(
        a=frame_board_dimensions,
        b=(-2.0, -2.0, -2.0),
        addend=dimensions,
    )

    box_dimensions = pf.nodes.math.vector_multiply_add(
        a=back_width.astype(dtype=pf.Vector),
        b=(1.0, 0.0, 0.0),
        addend=dim_sub_2frame * (0.0, 1.0, 1.0),
    )

    box_result = _box(
        dimensions=box_dimensions, origin=frame_board_dimensions * (0.0, 1.0, 1.0)
    )
    enable_back = pf.nodes.func.switch(switch=enable_back_switch, a=box_result)

    grid_1 = n_spaces_y.astype(dtype=float) + 1.0

    grid_0 = n_spaces_z.astype(dtype=float) + 1.0
    grid_with_indices_result = _grid_with_indices(
        vertices_x=grid_1.astype(dtype=int),
        vertices_y=grid_0.astype(dtype=int),
    )
    transform = pf.nodes.geo.transform(
        geometry=grid_with_indices_result.mesh,
        rotation=(1.570796, 0.0, 1.570796),
    )

    input_position = pf.nodes.geo.input_position()

    offset_forward_avoid_backplate = pf.nodes.math.vector_scale(
        vector=(1.0, 0.0, 0.0), scale=back_width
    )

    bottomleft_interior_point = frame_board_dimensions * (0.0, 1.0, 1.0)

    set_position_position_to_min = pf.nodes.math.vector_multiply_add(
        a=row_divider_width.astype(dtype=pf.Vector),
        b=(0.0, 0.0, -0.5),
        addend=offset_forward_avoid_backplate + bottomleft_interior_point,
    )

    topright_interior_point = pf.nodes.math.vector_multiply_add(
        a=frame_board_dimensions,
        b=(0.0, -1.0, -1.0),
        addend=dimensions,
    )

    set_position_position_to_max = pf.nodes.math.vector_multiply_add(
        a=row_divider_width.astype(dtype=pf.Vector),
        b=(0.0, 0.0, 0.5),
        addend=topright_interior_point + offset_forward_avoid_backplate,
    )

    set_position_position = pf.nodes.math.map_range(
        value=input_position,
        from_max=(1.0, 1.0, 1.0),
        from_min=(0.0, 0.0, 0.0),
        to_max=set_position_position_to_max,
        to_min=set_position_position_to_min,
    )
    set_position = pf.nodes.geo.set_position(
        geometry=transform, position=set_position_position
    )
    is_left = pf.nodes.func.equal(a=grid_with_indices_result.index_x, b=0)

    is_bottom = pf.nodes.func.equal(a=grid_with_indices_result.index_y, b=0)
    is_top = pf.nodes.func.equal(a=grid_with_indices_result.index_y, b=n_spaces_z)
    instance_b_a = pf.nodes.func.boolean_or(a=is_bottom, b=is_top)

    instance_b_1 = pf.nodes.func.boolean_not(instance_b_a)
    instance_horizontal_boards_selection = pf.nodes.func.boolean_and(
        a=is_left, b=instance_b_1
    )
    vert_board_dimensions_x = dimensions.x - back_width

    hor_board_dims_y = pf.nodes.math.multiply_add(
        a=frame_board_dimensions.y, b=-2.0, addend=dimensions.y
    )

    hor_board_dims = pf.nodes.math.combine_xyz(
        x=vert_board_dimensions_x,
        y=hor_board_dims_y,
        z=row_divider_width,
    )
    box_1 = n_spaces_y.astype(dtype=float) + 1.0

    box_result_1 = _box(
        dimensions=hor_board_dims,
        origin=row_divider_width.astype(dtype=pf.Vector) * (0.0, 0.0, -0.5),
        vertices_y=box_1.astype(dtype=int),
    )
    instance_horizontal_boards = pf.nodes.geo.instance_on_points(
        points=set_position,
        instance=box_result_1,
        selection=instance_horizontal_boards_selection,
    )

    is_right = pf.nodes.func.equal(a=grid_with_indices_result.index_x, b=n_spaces_y)

    instance_a_a = pf.nodes.func.boolean_or(a=is_left, b=is_right)

    instance_a = pf.nodes.func.boolean_not(instance_a_a)
    instance_b_0 = pf.nodes.func.boolean_not(is_top)
    instance_vertical_boards_selection = pf.nodes.func.boolean_and(
        a=instance_a, b=instance_b_0
    )
    vert_board_dimensions = pf.nodes.math.combine_xyz(
        x=vert_board_dimensions_x,
        y=col_divider_width,
        z=cell_clearance,
    )
    vert_board_origin = pf.nodes.math.vector_multiply_add(
        a=col_divider_width.astype(dtype=pf.Vector),
        b=(0.0, -0.5, 0.0),
        addend=row_divider_width.astype(dtype=pf.Vector) * (0.0, 0.0, 0.5),
    )
    vert_board = _box_even(dimensions=vert_board_dimensions, origin=vert_board_origin)
    instance_vertical_boards = pf.nodes.geo.instance_on_points(
        points=set_position,
        instance=vert_board,
        selection=instance_vertical_boards_selection,
    )

    join = pf.nodes.geo.join_geometry(
        [join_sides, enable_back, instance_horizontal_boards, instance_vertical_boards]
    )

    realize_instances = pf.nodes.geo.realize_instances(join)

    return realize_instances


def storage_cell_shelf(
    dimensions: pf.Vector | None = None,
    n_spaces_y: int = 3,
    n_spaces_z: int = 4,
    frame_thickness: float = 0.03,
    row_divider_width: float = 0.025,
    col_divider_width: float = 0.02,
    back_width: float = 0.02,
    frame_material: pf.Material | None = None,
) -> StorageResult:
    if dimensions is None:
        dimensions = pf.Vector((0.35, 1.2, 1.6))
    if frame_material is None:
        frame_material = pf.Material(surface=pf.nodes.shader.principled_bsdf())
    geo = _shelf_geometry(
        dimensions=dimensions,
        n_spaces_y=n_spaces_y,
        n_spaces_z=n_spaces_z,
        frame_board_dimensions=(frame_thickness, frame_thickness, frame_thickness),
        row_divider_width=row_divider_width,
        col_divider_width=col_divider_width,
        back_width=back_width,
    )
    geo = pf.nodes.geo.set_material(geometry=geo, material=frame_material)
    geo = crease_sharp(geo, threshold_degrees=30.0)
    result = pf.nodes.to_mesh_object(geo)
    pf.ops.modifier.bevel(result, width=0.003, segments=2)
    pf.ops.modifier.subdivide_surface(result, levels=2, _skip_apply=True)
    return StorageResult(mesh=result)


def storage_dimensions_and_cell_counts_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
) -> tuple[pf.Vector, int, int]:
    """Storage footprint and the cell grid that fits it, coupled so cells stay usable."""
    if dimensions is None:
        depth = pf.random.uniform(rng, 0.25, 0.45)
        width = pf.random.uniform(rng, 0.7, 2.5)
        height = pf.random.uniform(rng, 0.8, 2.2)
        dimensions = pf.Vector((depth, width, height))

    # sample goal cell dims, then fit cell counts to best match overall dimensions;
    # goal width ranges up to the full width so a single full-width row stays an option
    if n_spaces_y is None:
        goal_cell_width = pf.random.uniform(rng, 0.3, max(0.6, dimensions[1]))
        n_spaces_y = max(1, round(dimensions[1] / goal_cell_width))
    if n_spaces_z is None:
        goal_cell_height = pf.random.uniform(rng, 0.375, 0.45)
        n_spaces_z = max(1, round(dimensions[2] / goal_cell_height))
    return dimensions, n_spaces_y, n_spaces_z


def storage_cell_shelf_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    frame_material: pf.Material | None = None,
    back_width: float | None = None,
) -> StorageResult:
    dimensions, n_spaces_y, n_spaces_z = storage_dimensions_and_cell_counts_rand(
        rng, dimensions, n_spaces_y, n_spaces_z
    )
    frame_thickness = pf.random.uniform(rng, 0.02, 0.06)
    row_divider_width = pf.random.uniform(rng, 0.015, 0.05)
    col_divider_width = pf.random.uniform(rng, 0.01, 0.04)
    if back_width is None:
        rng_choice, rng_back = rng.spawn(2)
        back_width = pf.control.choice(
            rng_choice,
            [
                (0.0, 0.5),
                (pf.random.uniform(rng_back, 0.01, 0.04), 0.5),
            ],
        )

    vec = pf.nodes.shader.coord().uv
    if frame_material is None:
        (rng_mat,) = rng.spawn(1)
        frame_material = furniture_material_rand(rng_mat, vec)

    geo = _shelf_geometry(
        dimensions=dimensions,
        n_spaces_y=n_spaces_y,
        n_spaces_z=n_spaces_z,
        frame_board_dimensions=(frame_thickness, frame_thickness, frame_thickness),
        row_divider_width=row_divider_width,
        col_divider_width=col_divider_width,
        back_width=back_width,
    )
    geo = pf.nodes.geo.set_material(geometry=geo, material=frame_material)
    geo = crease_sharp(geo, threshold_degrees=30.0)
    result = pf.nodes.to_mesh_object(geo)
    pf.ops.modifier.bevel(
        result, width=pf.random.uniform(rng, 0.001, 0.005), segments=2
    )
    pf.ops.modifier.subdivide_surface(result, levels=2, _skip_apply=True)
    return StorageResult(mesh=result)


def cabinet_with_base(
    dimensions: pf.Vector | None = None,
    base_height: float = 0.0762,
    leg_diameter: float = 0.0762,
    frame_material: pf.Material | None = None,
) -> StorageResult:
    """Cabinet carcass raised on a leg base occupying the bottom base_height of
    the overall height."""
    if dimensions is None:
        dimensions = pf.Vector((0.3, 0.5, 1.2))
    if frame_material is None:
        frame_material = pf.Material(surface=pf.nodes.shader.principled_bsdf())
    depth, width, height = dimensions.x, dimensions.y, dimensions.z
    carcass = storage_cell_shelf(
        dimensions=pf.Vector((depth, width, height - base_height)),
        frame_material=frame_material,
    ).mesh
    pf.ops.object.set_transform(carcass, location=(0.0, 0.0, base_height))
    base = table.base_square(
        dimensions=pf.Vector((width, depth, base_height)),
        leg_diameter=leg_diameter,
    ).mesh
    pf.ops.object.set_material(
        base, surface=frame_material.surface, displacement=frame_material.displacement
    )
    # bases separate their frames along local x, so turn that across the width
    pf.ops.object.set_transform(
        base,
        location=(depth * 0.5, width * 0.5, 0.0),
        rotation_euler=(0.0, 0.0, math.pi / 2),
    )
    pf.ops.object.join(carcass, base)
    return StorageResult(mesh=carcass)


def cabinet_with_base_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    rng, rng_shelves, rng_mat, rng_base_sel, rng_base = rng.spawn(5)
    if dimensions is None:
        depth = pf.random.uniform(rng, 0.25, 0.35)
        width = pf.random.uniform(rng, 0.3, 0.55)
        height = pf.random.uniform(rng, 0.9, 1.8)
        dimensions = pf.Vector((depth, width, height))
    depth, width, height = dimensions.x, dimensions.y, dimensions.z

    frame_material = furniture_material_rand(rng_mat, pf.nodes.shader.coord().uv)
    base_height = pf.random.uniform(rng, 0.0254, 0.1524)
    leg_diameter = pf.random.uniform(rng, 0.0508, 0.127)

    carcass = storage_cell_shelf_rand(
        rng_shelves,
        dimensions=pf.Vector((depth, width, height - base_height)),
        frame_material=frame_material,
    ).mesh
    pf.ops.object.set_transform(carcass, location=(0.0, 0.0, base_height))
    base_fn = pf.control.choice(
        rng_base_sel, [(table.base_square_rand, 1.0), (table.base_straight_rand, 1.0)]
    )
    base = base_fn(
        rng_base,
        dimensions=pf.Vector((width, depth, base_height)),
        material=frame_material,
        leg_diameter=leg_diameter,
        leg_placement_bottom_scale=1.0,
    ).mesh
    # bases separate their frames along local x, so turn that across the width
    pf.ops.object.set_transform(
        base,
        location=(depth * 0.5, width * 0.5, 0.0),
        rotation_euler=(0.0, 0.0, math.pi / 2),
    )
    pf.ops.object.join(carcass, base)
    return StorageResult(mesh=carcass)


@pf.nodes.node_function
def _grid_legs(
    depth: t.SocketOrVal[float],
    width: t.SocketOrVal[float],
    height: t.SocketOrVal[float],
    margin_frac: t.SocketOrVal[float],
    spacing_frac: t.SocketOrVal[float],
    diameter: t.SocketOrVal[float],
) -> pf.ProcNode:
    margin_x = depth * margin_frac
    margin_y = width * margin_frac
    n_x = pf.nodes.math.clamp(
        pf.nodes.math.floor((depth - 2.0 * margin_x) / spacing_frac) + 1.0,
        2.0,
        5.0,
    ).astype(dtype=int)
    n_y = pf.nodes.math.clamp(
        pf.nodes.math.floor((width - 2.0 * margin_y) / spacing_frac) + 1.0,
        2.0,
        5.0,
    ).astype(dtype=int)
    span_x = depth - 2.0 * margin_x - diameter
    span_y = width - 2.0 * margin_y - diameter
    grid = pf.nodes.geo.mesh_grid(
        size_x=span_x,
        size_y=span_y,
        vertices_x=n_x,
        vertices_y=n_y,
    )
    position = pf.nodes.geo.input_position()
    interior_x = pf.nodes.func.less_than(
        a=pf.nodes.math.absolute(position.x), b=span_x * 0.5 - 1e-4
    )
    interior_y = pf.nodes.func.less_than(
        a=pf.nodes.math.absolute(position.y), b=span_y * 0.5 - 1e-4
    )
    interior = pf.nodes.func.boolean_and(a=interior_x, b=interior_y)
    boundary = pf.nodes.geo.delete_geometry(
        geometry=grid.mesh, selection=interior, domain="POINT"
    )
    points = pf.nodes.geo.transform(
        boundary,
        translation=pf.nodes.math.combine_xyz(
            x=depth * 0.5 - diameter * 0.5,
            y=width * 0.5 - diameter * 0.5,
        ),
    )
    leg = _box(dimensions=pf.nodes.math.combine_xyz(x=diameter, y=diameter, z=height))
    return pf.nodes.geo.realize_instances(
        pf.nodes.geo.instance_on_points(points=points, instance=leg)
    )


def grid_legs_rand(
    rng: pf.RNG,
    dimensions: pf.Vector,
    leg_height: t.SocketOrVal[float],
    close_edges: bool = False,
    diameter: float | None = None,
) -> pf.MeshObject:
    depth = dimensions[0]
    width = dimensions[1]
    if close_edges:
        margin_frac = pf.random.uniform(rng, 0.04, 0.08)
    else:
        margin_frac = pf.random.uniform(rng, 0.08, 0.16)
    max_spacing = pf.nodes.math.maximum(depth, width) * 0.55
    spacing_frac = pf.random.clip_gaussian(rng, 0.5, 0.3, 0.25, max_spacing)
    if diameter is None:
        diameter = pf.random.uniform(rng, 0.025, 0.14)
    return pf.nodes.to_mesh_object(
        _grid_legs(depth, width, leg_height, margin_frac, spacing_frac, diameter)
    )


def _table_base_rand(
    rng: pf.RNG,
    dimensions: pf.Vector,
    leg_height: t.SocketOrVal[float],
    close_edges: bool = False,
) -> pf.MeshObject:
    # keep-local: table imports storage for coffee-table composition.
    from infinigen2.objects import table

    rng_choice, rng_base = rng.spawn(2)
    depth = dimensions[0]
    width = dimensions[1]
    base_fn = pf.control.choice(
        rng_choice,
        [(table.base_straight_rand, 1.0), (table.base_square_rand, 1.0)],
    )
    base_result = base_fn(
        rng_base,
        dimensions=(depth * 0.96, width * 0.96, leg_height),
        close_edges=close_edges,
    )
    base_min = pf.ops.attr.bbox_min_max(base_result.mesh, global_coords=False)[0]
    pf.ops.object.set_transform(
        base_result.mesh,
        location=(depth * 0.5, width * 0.5, base_min[2] * -1.0),
    )
    return base_result.mesh


def stable_legs_rand(
    rng: pf.RNG,
    dimensions: pf.Vector,
    leg_height: t.SocketOrVal[float],
    close_edges: bool = False,
) -> pf.MeshObject:
    rng_choice, rng_base = rng.spawn(2)
    fn = pf.control.choice(
        rng_choice,
        [(grid_legs_rand, 0.4), (_table_base_rand, 0.6)],
    )
    return fn(rng_base, dimensions, leg_height, close_edges=close_edges)


def storage_with_legs_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    frame_material: pf.Material | None = None,
    back_width: float | None = None,
    leg_height: float | None = None,
    close_edges: bool = False,
) -> StorageResult:
    """Cell shelf raised on a stable compositional base."""
    rng, rng_body, rng_legs = rng.spawn(3)
    dimensions, n_spaces_y, n_spaces_z = storage_dimensions_and_cell_counts_rand(
        rng, dimensions, n_spaces_y, n_spaces_z
    )
    if leg_height is None:
        leg_height = pf.random.uniform(rng, 0.15, 0.3)
    body_dimensions = pf.Vector(
        (dimensions[0], dimensions[1], dimensions[2] - leg_height)
    )
    body_result = storage_cell_shelf_rand(
        rng_body,
        dimensions=body_dimensions,
        n_spaces_y=n_spaces_y,
        n_spaces_z=n_spaces_z,
        frame_material=frame_material,
        back_width=back_width,
    )
    pf.ops.object.set_transform(body_result.mesh, location=(0.0, 0.0, leg_height))
    legs = stable_legs_rand(rng_legs, dimensions, leg_height, close_edges=close_edges)
    pf.ops.object.join(body_result.mesh, legs)
    return StorageResult(mesh=body_result.mesh)


def storage_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
    n_spaces_y: int | None = None,
    n_spaces_z: int | None = None,
    frame_material: pf.Material | None = None,
    back_width: float | None = None,
) -> StorageResult:
    """Cell shelf, half of them raised on a stable compositional base."""
    rng, rng_choice, rng_storage = rng.spawn(3)
    dimensions, n_spaces_y, n_spaces_z = storage_dimensions_and_cell_counts_rand(
        rng, dimensions, n_spaces_y, n_spaces_z
    )
    storage_func = pf.control.choice(
        rng_choice,
        [(storage_cell_shelf_rand, 1.0), (storage_with_legs_rand, 1.0)],
    )
    return storage_func(
        rng_storage,
        dimensions=dimensions,
        n_spaces_y=n_spaces_y,
        n_spaces_z=n_spaces_z,
        frame_material=frame_material,
        back_width=back_width,
    )


def storage_bench_rand(
    rng: pf.RNG,
    dimensions: pf.Vector | None = None,
) -> StorageResult:
    """Outward-facing storage bench at dining-seat height."""
    if dimensions is None:
        dimensions = pf.Vector(
            (
                pf.random.uniform(rng, 0.38, 0.48),
                pf.random.uniform(rng, 0.9, 2.5),
                pf.random.uniform(rng, 0.42, 0.5),
            )
        )
    return storage_with_legs_rand(
        rng,
        dimensions=dimensions,
        n_spaces_y=pf.random.randint(rng, 2, 8),
        n_spaces_z=1,
        leg_height=dimensions[2] * pf.random.uniform(rng, 0.15, 0.35),
        close_edges=True,
    )


def storage_coffee_table_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    """Coffee table whose body is a cell shelf."""
    # keep-local: table imports storage for coffee-table composition.
    from infinigen2.objects import table

    if dimensions is None:
        dimensions = pf.Vector(table.coffee_table_dimensions_rand(rng))
    return storage_with_legs_rand(
        rng,
        dimensions=dimensions,
        n_spaces_y=pf.random.randint(rng, 2, 4),
        n_spaces_z=1,
        leg_height=dimensions[2] * pf.random.uniform(rng, 0.3, 0.7),
    )


def storage_side_table_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    """Side table whose body is a cell shelf."""
    # keep-local: table imports storage for coffee-table composition.
    from infinigen2.objects import table

    if dimensions is None:
        dimensions = pf.Vector(table.side_table_dimensions_rand(rng))
    result = storage_with_legs_rand(
        rng,
        dimensions=dimensions,
        n_spaces_y=pf.random.randint(rng, 1, 3),
        n_spaces_z=1,
        leg_height=dimensions[2] * pf.random.uniform(rng, 0.25, 0.55),
    )
    center_footprint(result.mesh)
    return result


def cabinet_with_door(
    dimensions: pf.Vector | None = None,
    frame_material: pf.Material | None = None,
) -> StorageResult:
    if dimensions is None:
        dimensions = pf.Vector((0.3, 0.5, 1.2))
    if frame_material is None:
        frame_material = pf.Material(surface=pf.nodes.shader.principled_bsdf())
    thickness = 0.019
    depth, width, height = dimensions.x, dimensions.y, dimensions.z
    shelf_dimensions = pf.Vector((depth - thickness, width, height))
    carcass_result = storage_cell_shelf(
        dimensions=shelf_dimensions, frame_material=frame_material
    )
    door_result = door_with_handle(
        dimensions=pf.Vector((thickness, width, height)),
        material=frame_material,
    )
    pf.ops.object.set_transform(
        door_result.mesh, location=(depth - thickness, 0.0, 0.0)
    )
    pf.ops.object.join(carcass_result.mesh, door_result.mesh)
    return StorageResult(mesh=carcass_result.mesh)


def cabinet_with_door_rand(
    rng: pf.RNG, dimensions: pf.Vector | None = None
) -> StorageResult:
    rng, rng_shelves, rng_front, rng_mat, rng_front_mat, rng_handle = rng.spawn(6)
    if dimensions is None:
        depth = pf.random.uniform(rng, 0.25, 0.35)
        # cap width to v1's single-door range so one door stays a realistic panel
        width = pf.random.uniform(rng, 0.3, 0.55)
        height = pf.random.uniform(rng, 0.9, 1.8)
        dimensions = pf.Vector((depth, width, height))
    depth, width, height = dimensions.x, dimensions.y, dimensions.z

    vec = pf.nodes.shader.coord().uv
    frame_material = furniture_material_rand(rng_mat, vec)

    def _match_carcass(rng: pf.RNG) -> pf.Material:
        return frame_material

    def _own_material(rng: pf.RNG) -> pf.Material:
        return furniture_material_rand(rng, vec)

    rng_front_mat, rng_inner_mat = rng_front_mat.spawn(2)
    front_material = pf.control.choice(
        rng_front_mat, [(_match_carcass, 2.0), (_own_material, 1.0)]
    )(rng_front_mat)

    def _glazed(rng: pf.RNG) -> pf.Material:
        return glass_material_rand(rng, vec)

    def _solid(rng: pf.RNG) -> pf.Material:
        return front_material

    inner_material = pf.control.choice(rng_inner_mat, [(_glazed, 0.4), (_solid, 0.6)])(
        rng_inner_mat
    )

    thickness = pf.random.uniform(rng, 0.016, 0.022)
    shelf_dimensions = pf.Vector((depth - thickness, width, height))
    carcass_result = storage_cell_shelf_rand(
        rng_shelves, dimensions=shelf_dimensions, frame_material=frame_material
    )
    rng_handle, rng_handle_choice = rng_handle.spawn(2)
    handle_func = pf.control.choice(
        rng_handle_choice,
        [
            (handles.bar_pull_handle_rand, 6.0),
            (handles.curved_pull_handle_rand, 4.0),
            (handles.knob_handle_rand, 2.0),
            (handles.lever_handle_rand, 1.0),
        ],
    )
    door_result = door_composite_rand(
        rng_front,
        dimensions=pf.Vector((thickness, width, height)),
        material=front_material,
        inner_material=inner_material,
        handle=handle_func(rng_handle).mesh,
    )
    pf.ops.object.set_transform(
        door_result.mesh, location=(depth - thickness, 0.0, 0.0)
    )
    pf.ops.object.join(carcass_result.mesh, door_result.mesh)
    return StorageResult(mesh=carcass_result.mesh)
