# Copyright (C) 2026, Princeton University.
# This source code is licensed under the BSD 3-Clause license found in the LICENSE file in the root directory of this source tree.

# Authors:
# - Alexander Raistrick: refactor for Infinigen2

from typing import NamedTuple

import procfunc as pf
from procfunc.nodes import types as t

__all__ = [
    "leaf",
    "leaf_color_rand",
    "leaf_preset",
    "leaf_rand",
    "leaf_ridged_preset",
    "leaf_rounded_sections_preset",
    "leaf_streaks_preset",
    "leaf_velvet_preset",
]


class VeinLevel0Result(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    cell_id: pf.ProcNode[pf.Vector]
    mask: pf.ProcNode[float]
    clearance: pf.ProcNode[float]
    height: pf.ProcNode[float]


@pf.nodes.node_function
def _vein_level_0(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    max_thickness: t.SocketOrVal[float] = 0.02,
    min_thickness: t.SocketOrVal[float] = 0.01,
    max_height: t.SocketOrVal[float] = 0.0005,
    min_height: t.SocketOrVal[float] = 0.0002,
    vein_clearance: t.SocketOrVal[float] = 0.2,
    gab_height: t.SocketOrVal[float] = 0.0,
    sharpness: t.SocketOrVal[float] = 0.75,
    alpha: t.SocketOrVal[float] = 1.0,
) -> VeinLevel0Result:
    # Code generated by procfunc v0.30.1
    cell_id = pf.nodes.math.combine_xyz(vector.x > 0.5)
    mask_value_value = pf.nodes.math.absolute(vector.x - 0.5)
    mask_value_from_max = pf.nodes.math.mix(
        a=max_thickness, b=min_thickness, factor=vector.y
    )
    mask_value = pf.nodes.math.map_range(
        value=mask_value_value, from_max=mask_value_from_max
    )
    mask_from_min = pf.nodes.math.minimum(a=sharpness, b=0.99999)
    mask = pf.nodes.math.map_range(
        value=mask_value,
        from_min=mask_from_min,
        to_max=0.0,
        to_min=alpha,
    )
    clearance_a = pf.nodes.math.maximum(a=mask_value_value - mask_value_from_max, b=0.0)
    clearance_value_value = pf.nodes.math.map_range(
        value=clearance_a * 2.0,
        from_max=vein_clearance,
        to_max=0.0,
        to_min=1.0,
    )
    clearance_value = pf.nodes.math.acos(clearance_value_value)
    clearance = pf.nodes.math.sin(clearance_value)
    height_a_a_a = pf.nodes.math.map_range(value=vector.y, from_max=0.5)
    height_a_a_b = pf.nodes.math.map_range(
        value=vector.y, from_min=0.5, to_max=0.0, to_min=1.0
    )
    height_a_a = pf.nodes.math.minimum(a=height_a_a_a, b=height_a_a_b)
    height_a_0 = (height_a_a**0.333) * clearance
    height_b_value = pf.nodes.math.acos(mask_value)
    height_b_1 = pf.nodes.math.sin(height_b_value)
    height_b_0 = pf.nodes.math.mix(a=max_height, b=min_height, factor=vector.y)
    height = (gab_height * height_a_0) + (height_b_1 * height_b_0)
    return VeinLevel0Result(vector, cell_id, mask, clearance, height)


class CoordWarpResult(NamedTuple):
    vector: pf.ProcNode[pf.Vector]
    fac: pf.ProcNode[float]


@pf.nodes.node_function
def _coord_warp(
    coord: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    size: t.SocketOrVal[float] = 0.1,
    strength: t.SocketOrVal[float] = 0.5,
    detail: t.SocketOrVal[float] = 4.0,
    w: t.SocketOrVal[float] = 0.0,
) -> CoordWarpResult:
    # Code generated by procfunc v0.30.1
    vector_a_b = pf.nodes.math.combine_xyz(z=w)
    vector_a = coord + vector_a_b
    noise = pf.nodes.texture.noise(vector=vector_a, scale=1.0 / size, detail=detail)
    vector_b = pf.nodes.math.vector_scale(
        vector=noise.color.astype(dtype=pf.Vector) - (0.5, 0.5, 0.5),
        scale=size * strength,
    )
    vector = vector_a + vector_b
    return CoordWarpResult(vector, noise.fac)


class VeinLevel1ParallelResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    cell_id: pf.ProcNode[pf.Vector]
    mask: pf.ProcNode[float]
    clearance: pf.ProcNode[float]
    height: pf.ProcNode[float]


@pf.nodes.node_function
def _vein_level_1_parallel(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    base_cell_id: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    base_mask: t.SocketOrVal[float] = 0.0,
    base_clearance: t.SocketOrVal[float] = 0.0,
    base_height: t.SocketOrVal[float] = 0.0,
    vein_settings_rotation: t.SocketOrVal[float] = -0.603884,
    vein_settings_spacing: t.SocketOrVal[float] = 0.1,
    vein_settings_randomness: t.SocketOrVal[float] = 0.641667,
    vein_settings_left_offset: t.SocketOrVal[float] = 0.0,
    vein_settings_right_offset: t.SocketOrVal[float] = 0.0,
    vein_settings_shear: t.SocketOrVal[float] = 0.0,
    vein_settings_curvature: t.SocketOrVal[float] = 3.0,
    vein_settings_max_thickness: t.SocketOrVal[float] = 0.05,
    vein_settings_min_thickness: t.SocketOrVal[float] = 0.01,
    vein_settings_max_height: t.SocketOrVal[float] = 0.0002,
    vein_settings_min_height: t.SocketOrVal[float] = 0.0,
    vein_settings_vein_clearance: t.SocketOrVal[float] = 0.37,
    vein_settings_sharpness: t.SocketOrVal[float] = 0.5,
    vein_settings_gab_height: t.SocketOrVal[float] = 0.0,
    vein_settings_alpha: t.SocketOrVal[float] = 1.0,
    distortion_size: t.SocketOrVal[float] = 0.5,
    distortion_strength: t.SocketOrVal[float] = 0.3,
    distortion_detail: t.SocketOrVal[float] = 3.0,
    distortion_w: t.SocketOrVal[float] = 0.0,
) -> VeinLevel1ParallelResult:
    # Code generated by procfunc v0.30.1
    voronoi_distance_w_factor = vector.x > 0.5
    coord_warp_coord_y = pf.nodes.math.mix(
        a=vein_settings_left_offset,
        b=vein_settings_right_offset,
        factor=voronoi_distance_w_factor,
    )
    coord_warp_coord = pf.nodes.math.combine_xyz(y=coord_warp_coord_y)
    coord_warp_result = _coord_warp(
        coord=vector + coord_warp_coord,
        size=distortion_size,
        strength=distortion_strength,
        detail=distortion_detail,
        w=distortion_w,
    )
    mask_factor_a = pf.nodes.math.absolute(vector.x - 0.5)
    mask_factor = mask_factor_a * 2.0
    voronoi_y_0 = mask_factor**vein_settings_curvature
    voronoi_0_vector_b = pf.nodes.math.combine_xyz(y=vein_settings_shear * voronoi_y_0)
    voronoi_0_vector = coord_warp_result.vector - voronoi_0_vector_b
    voronoi_2 = pf.nodes.math.vector_rotate_axis_angle(voronoi_0_vector)
    voronoi_1 = pf.nodes.math.vector_rotate_axis_angle(voronoi_0_vector)
    voronoi_distance_w = pf.nodes.math.mix(
        a=voronoi_2.y, b=voronoi_1.y, factor=voronoi_distance_w_factor
    )
    voronoi_distance_scale = 1.0 / vein_settings_spacing
    voronoi = pf.nodes.texture.voronoi(
        vector=None,
        scale=voronoi_distance_scale,
        randomness=vein_settings_randomness,
        voronoi_dimensions="1D",
        w=voronoi_distance_w,
    )
    cell_id_b = pf.nodes.math.combine_xyz(y=voronoi.color.astype(dtype=pf.Vector).y)
    cell_id = base_cell_id + cell_id_b
    voronoi_distance = pf.nodes.texture.voronoi_distance(
        vector=None,
        scale=voronoi_distance_scale,
        randomness=vein_settings_randomness,
        normalize=True,
        voronoi_dimensions="1D",
        w=voronoi_distance_w,
    )
    mask_b_value_from_max = pf.nodes.math.mix(
        a=vein_settings_max_thickness,
        b=vein_settings_min_thickness,
        factor=mask_factor,
    )
    mask_b_value = pf.nodes.math.map_range(
        value=voronoi_distance, from_max=mask_b_value_from_max
    )
    mask_b_from_min = pf.nodes.math.minimum(a=vein_settings_sharpness, b=0.99999)
    mask_b_0 = pf.nodes.math.map_range(
        value=mask_b_value,
        from_min=mask_b_from_min,
        to_max=0.0,
        to_min=vein_settings_alpha,
    )
    mask = pf.nodes.math.maximum(a=base_mask, b=mask_b_0)
    clearance_b_0 = pf.nodes.math.map_range(
        value=voronoi_distance - mask_b_value_from_max,
        from_max=vein_settings_vein_clearance,
    )
    clearance_a_value = pf.nodes.math.acos(1.0 - clearance_b_0)
    clearance_a = pf.nodes.math.sin(clearance_a_value)
    clearance = clearance_a * base_clearance
    height_a_a_value = pf.nodes.math.acos(mask_b_value)
    height_a_a_1 = pf.nodes.math.sin(height_a_a_value)
    height_a_a_0 = pf.nodes.math.mix(
        a=vein_settings_max_height,
        b=vein_settings_min_height,
        factor=mask_factor,
    )
    height_a_b = base_mask > 0.0
    height_a = pf.nodes.math.maximum(
        a=height_a_a_1 * height_a_a_0, b=height_a_b * base_height
    )
    height_b_b = pf.nodes.math.mix(
        a=vein_settings_gab_height, b=0.0, factor=mask_factor
    )
    height_b_1 = clearance * height_b_b
    height_b_0 = (1.0 - height_a_b) * base_height
    height = height_a + (height_b_1 + height_b_0)
    return VeinLevel1ParallelResult(vector, cell_id, mask, clearance, height)


class VeinLevel2CellResult(NamedTuple):
    vector: t.SocketOrVal[pf.Vector]
    cell_id: pf.ProcNode[pf.Vector]
    mask: pf.ProcNode[float]
    clearance: pf.ProcNode[float]
    height: pf.ProcNode[float]


@pf.nodes.node_function
def _vein_level_2_cell(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    base_cell_id: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    base_mask: t.SocketOrVal[float] = 0.0,
    base_clearance: t.SocketOrVal[float] = 0.0,
    base_height: t.SocketOrVal[float] = 0.0,
    vein_settings_spacing: t.SocketOrVal[float] = 0.058824,
    vein_settings_max_thickness: t.SocketOrVal[float] = 0.02,
    vein_settings_min_thickness: t.SocketOrVal[float] = 0.0,
    vein_settings_max_height: t.SocketOrVal[float] = 2e-05,
    vein_settings_min_height: t.SocketOrVal[float] = 0.0,
    vein_settings_vein_clearance: t.SocketOrVal[float] = 0.31,
    vein_settings_sharpness: t.SocketOrVal[float] = 0.5,
    vein_settings_gab_height: t.SocketOrVal[float] = 0.0,
    vein_settings_alpha: t.SocketOrVal[float] = 1.0,
    distortion_size: t.SocketOrVal[float] = 0.19,
    distortion_strength: t.SocketOrVal[float] = 0.74,
    distortion_detail: t.SocketOrVal[float] = 1.0,
    distortion_w: t.SocketOrVal[float] = 0.0,
) -> VeinLevel2CellResult:
    # Code generated by procfunc v0.30.1
    coord_warp_result = _coord_warp(
        coord=vector,
        size=distortion_size,
        strength=distortion_strength,
        detail=distortion_detail,
        w=distortion_w,
    )
    white_noise = pf.nodes.texture.white_noise(
        vector=base_cell_id, noise_dimensions="2D"
    )
    voronoi_vector = coord_warp_result.vector / (
        1.0,
        1.0,
        1.0,
    ) + white_noise.color.astype(dtype=pf.Vector)
    voronoi_scale = 1.0 / vein_settings_spacing
    voronoi = pf.nodes.texture.voronoi(
        vector=voronoi_vector,
        scale=voronoi_scale,
        roughness=0.491667,
        lacunarity=1.3,
        normalize=True,
        voronoi_dimensions="2D",
    )
    cell_id = voronoi.color.astype(dtype=pf.Vector)
    voronoi_distance = pf.nodes.texture.voronoi_distance(
        vector=voronoi_vector,
        scale=voronoi_scale,
        roughness=0.491667,
        lacunarity=1.3,
        normalize=True,
        voronoi_dimensions="2D",
    )
    mask_factor_a = pf.nodes.math.absolute(vector.x - 0.5)
    mask_factor = mask_factor_a * 2.0
    mask_b_value_from_max = pf.nodes.math.mix(
        a=vein_settings_max_thickness,
        b=vein_settings_min_thickness,
        factor=mask_factor,
    )
    mask_b_value = pf.nodes.math.map_range(
        value=voronoi_distance, from_max=mask_b_value_from_max
    )
    mask_b_from_min = pf.nodes.math.minimum(a=vein_settings_sharpness, b=0.99999)
    mask_b_0 = pf.nodes.math.map_range(
        value=mask_b_value,
        from_min=mask_b_from_min,
        to_max=0.0,
        to_min=vein_settings_alpha,
    )
    mask = pf.nodes.math.maximum(a=base_mask, b=mask_b_0)
    clearance_a_value_value = pf.nodes.math.map_range(
        value=voronoi_distance - mask_b_value_from_max,
        from_max=vein_settings_vein_clearance,
        to_max=0.0,
        to_min=1.0,
    )
    clearance_a_value = pf.nodes.math.acos(clearance_a_value_value)
    clearance_a = pf.nodes.math.sin(clearance_a_value)
    clearance = clearance_a * base_clearance
    height_a_a = base_mask > 0.0
    height_a_b_value = pf.nodes.math.acos(mask_b_value)
    height_a_b_1 = pf.nodes.math.sin(height_a_b_value)
    height_a_b_0 = pf.nodes.math.mix(
        a=vein_settings_max_height,
        b=vein_settings_min_height,
        factor=mask_factor,
    )
    height_a = pf.nodes.math.maximum(
        a=height_a_a * base_height, b=height_a_b_1 * height_a_b_0
    )
    height_b_1 = (1.0 - height_a_a) * base_height
    height_b_0 = clearance * vein_settings_gab_height
    height = height_a + (height_b_1 + height_b_0)
    return VeinLevel2CellResult(vector, cell_id, mask, clearance, height)


class ColorOffsetResult(NamedTuple):
    base_color: t.SocketOrVal[pf.Color]
    offset_color: pf.ProcNode[pf.Color]


@pf.nodes.node_function
def _color_offset(
    base_color: t.SocketOrVal[pf.Color] = pf.Color((0.8, 0.8, 0.8)),
    hue_offset: t.SocketOrVal[float] = 0.0,
    saturation: t.SocketOrVal[float] = 1.0,
    value: t.SocketOrVal[float] = 1.0,
) -> ColorOffsetResult:
    # Code generated by procfunc v0.30.1
    offset_color_hue = hue_offset + 1.0
    hue_saturation = pf.nodes.color.hue_saturation(
        fac=1.0,
        hue=offset_color_hue / 2.0,
        saturation=saturation,
        value=value,
        color=base_color,
    )
    return ColorOffsetResult(base_color, hue_saturation)


@pf.nodes.node_function
def _leaf_shader(
    mask: t.SocketOrVal[float] = 0.0,
    clearance: t.SocketOrVal[float] = 0.0,
    leaf_color_1: t.SocketOrVal[pf.Color] = pf.Color((0.031462, 0.134922, 0.019445)),
    leaf_color_2: t.SocketOrVal[pf.Color] = pf.Color((0.060292, 0.19861, 0.022054)),
    vein_color: t.SocketOrVal[pf.Color] = pf.Color((0.506151, 0.644078, 0.334624)),
    roughness: t.SocketOrVal[float] = 0.540909,
    specular_ior_level: t.SocketOrVal[float] = 1.0,
    translucency: t.SocketOrVal[float] = 0.125,
    sheen_weight: t.SocketOrVal[float] = 0.0,
    sheen_roughness: t.SocketOrVal[float] = 0.5,
    sheen_tint: t.SocketOrVal[pf.Color] = pf.Color((1.0, 1.0, 1.0)),
) -> pf.ProcNode[pf.Shader]:
    # Code generated by procfunc v0.30.1
    principled_base_color_a = pf.nodes.color.mix_rgb(
        factor=clearance, a=leaf_color_2, b=leaf_color_1
    )
    principled_base_color = pf.nodes.color.mix_rgb(
        factor=mask, a=principled_base_color_a, b=vein_color
    )
    principled = pf.nodes.shader.principled_bsdf(
        base_color=principled_base_color,
        roughness=roughness,
        subsurface_anisotropy=0.0,
        specular_ior_level=specular_ior_level,
        sheen_weight=sheen_weight,
        sheen_roughness=sheen_roughness,
        sheen_tint=sheen_tint,
    )
    translucent = pf.nodes.shader.translucent_bsdf(
        color=principled_base_color,
        normal=(0.0, 0.0, 0.0),
    )
    mix_shader = pf.nodes.shader.mix_shader(factor=translucency, a=None, b=translucent)
    add_shader = pf.nodes.shader.add_shader(a=principled, b=mix_shader)
    return add_shader


class FoliageLevel0HelperResult(NamedTuple):
    max_thickness: t.SocketOrVal[float]
    min_thickness: pf.ProcNode[float]
    max_height: pf.ProcNode[float]
    min_height: pf.ProcNode[float]
    vein_clearance: pf.ProcNode[float]


@pf.nodes.node_function
def _foliage_level_0_helper(
    max_thickness: t.SocketOrVal[float] = 0.01,
    min_thickness_scale: t.SocketOrVal[float] = 1.0,
    max_height_scale: t.SocketOrVal[float] = 0.1,
    min_height_scale: t.SocketOrVal[float] = 0.1,
    clearance_scale: t.SocketOrVal[float] = 20.0,
) -> FoliageLevel0HelperResult:
    # Code generated by procfunc v0.30.1
    min_thickness = max_thickness * min_thickness_scale
    max_height = max_thickness * max_height_scale
    min_height = min_thickness * min_height_scale
    vein_clearance = max_thickness * clearance_scale
    return FoliageLevel0HelperResult(
        max_thickness, min_thickness, max_height, min_height, vein_clearance
    )


class FoliageLevel12HelperResult(NamedTuple):
    spacing: t.SocketOrVal[float]
    max_thickness: t.SocketOrVal[float]
    min_thickness: pf.ProcNode[float]
    max_height: pf.ProcNode[float]
    min_height: pf.ProcNode[float]
    vein_clearance: pf.ProcNode[float]
    gap_height: pf.ProcNode[float]
    next_level_spacing: pf.ProcNode[float]


@pf.nodes.node_function
def _foliage_level_1_2_helper(
    primary_params_spacing: t.SocketOrVal[float] = 0.01,
    primary_params_max_thickness: t.SocketOrVal[float] = 1.0,
    other_params_min_thickness_scale: t.SocketOrVal[float] = 0.1,
    other_params_max_height_scale: t.SocketOrVal[float] = 0.1,
    other_params_min_height_scale: t.SocketOrVal[float] = 0.1,
    other_params_clearance_scale: t.SocketOrVal[float] = 0.1,
    other_params_gab_height_scale: t.SocketOrVal[float] = 0.01,
    other_params_next_level_scale: t.SocketOrVal[float] = 0.5,
) -> FoliageLevel12HelperResult:
    # Code generated by procfunc v0.30.1
    min_thickness = primary_params_max_thickness * other_params_min_thickness_scale
    max_height_a = primary_params_spacing * primary_params_max_thickness
    max_height = max_height_a * other_params_max_height_scale
    min_height = (max_height_a * min_thickness) * other_params_min_height_scale
    vein_clearance_b = 1.0 - primary_params_max_thickness
    vein_clearance = other_params_clearance_scale * vein_clearance_b
    gap_height = (
        vein_clearance_b * primary_params_spacing
    ) * other_params_gab_height_scale
    next_level_spacing = primary_params_spacing * other_params_next_level_scale
    return FoliageLevel12HelperResult(
        primary_params_spacing,
        primary_params_max_thickness,
        min_thickness,
        max_height,
        min_height,
        vein_clearance,
        gap_height,
        next_level_spacing,
    )


class LeafGrowthStreaksResult(NamedTuple):
    color: pf.ProcNode[pf.Color]
    height: pf.ProcNode[float]


@pf.nodes.node_function
def _leaf_growth_streaks(
    vector: t.SocketOrVal[pf.Vector] = (0.0, 0.0, 0.0),
    size: t.SocketOrVal[float] = 0.006667,
    detail: t.SocketOrVal[float] = 3.0,
    color_1: t.SocketOrVal[pf.Color] = pf.Color((0.012036, 0.167773, 0.015063)),
    color_2: t.SocketOrVal[pf.Color] = pf.Color((0.280539, 0.407728, 0.044441)),
    height: t.SocketOrVal[float] = 0.0,
    distortion_size: t.SocketOrVal[float] = 0.006667,
    distortion_strength: t.SocketOrVal[float] = 0.2,
    distortion_detail: t.SocketOrVal[float] = 3.0,
    distortion_w: t.SocketOrVal[float] = 0.0,
) -> LeafGrowthStreaksResult:
    # Code generated by procfunc v0.30.1
    coord_warp_result = _coord_warp(
        coord=vector,
        size=distortion_size,
        strength=distortion_strength,
        detail=distortion_detail,
        w=distortion_w,
    )
    voronoi = pf.nodes.texture.voronoi(
        vector=None,
        scale=1.0 / size,
        detail=detail,
        voronoi_dimensions="1D",
        w=coord_warp_result.vector.x,
    )
    color_4 = pf.nodes.color.separate_hsv(color_1)
    color_3 = pf.nodes.color.separate_hsv(color_2)
    color_factor_a_a = color_4.hue - color_3.hue
    color_factor_a_1 = color_factor_a_a > 0.0
    invert = 1.0 - color_factor_a_1
    color_factor_a_0 = pf.nodes.math.absolute(color_factor_a_a)
    color_factor = color_factor_a_0 > 0.5
    color_saturation_a_x = pf.nodes.math.mix(
        a=color_4.hue, b=color_4.hue + 1.0, factor=invert * color_factor
    )
    color_saturation_a = pf.nodes.math.combine_xyz(
        x=color_saturation_a_x,
        y=color_4.saturation,
        z=color_4.value,
    )
    color_saturation_b_x = pf.nodes.math.mix(
        a=color_3.hue,
        b=color_3.hue + 1.0,
        factor=color_factor_a_1 * color_factor,
    )
    color_saturation_b = pf.nodes.math.combine_xyz(
        x=color_saturation_b_x,
        y=color_3.saturation,
        z=color_3.value,
    )
    color_saturation = pf.nodes.math.mix(
        a=color_saturation_a,
        b=color_saturation_b,
        factor=voronoi.color.astype(dtype=pf.Vector),
        factor_mode="NON_UNIFORM",
    )
    color_hue = pf.nodes.math.fraction(color_saturation.x)
    color = pf.nodes.color.combine_hsv(
        hue=color_hue,
        saturation=color_saturation.y,
        value=color_saturation.z,
    )
    height_out = height * voronoi.distance
    return LeafGrowthStreaksResult(color, height_out)


def leaf_preset(vector: t.SocketOrVal[pf.Vector]) -> pf.Material:
    # Code generated by procfunc v0.30.1
    foliage_level_0_helper_result = _foliage_level_0_helper(
        max_height_scale=0.05, min_height_scale=0.05
    )
    vein_level_0_result = _vein_level_0(
        vector=vector,
        max_thickness=foliage_level_0_helper_result.max_thickness,
        min_thickness=foliage_level_0_helper_result.min_thickness,
        max_height=foliage_level_0_helper_result.max_height,
        min_height=foliage_level_0_helper_result.min_height,
        vein_clearance=foliage_level_0_helper_result.vein_clearance,
    )
    foliage_level_1_2_helper_result = _foliage_level_1_2_helper(
        primary_params_spacing=0.093478,
        primary_params_max_thickness=0.043478,
        other_params_min_thickness_scale=0.0,
        other_params_max_height_scale=0.05,
        other_params_min_height_scale=0.0,
        other_params_clearance_scale=0.399517,
        other_params_next_level_scale=0.640097,
    )
    vein_level_1_parallel_result = _vein_level_1_parallel(
        vector=vein_level_0_result.vector,
        base_cell_id=vein_level_0_result.cell_id,
        base_mask=vein_level_0_result.mask,
        base_clearance=vein_level_0_result.clearance,
        base_height=vein_level_0_result.height,
        vein_settings_rotation=0.614356,
        vein_settings_spacing=foliage_level_1_2_helper_result.spacing,
        vein_settings_randomness=1.0,
        vein_settings_max_thickness=foliage_level_1_2_helper_result.max_thickness,
        vein_settings_min_thickness=foliage_level_1_2_helper_result.min_thickness,
        vein_settings_max_height=foliage_level_1_2_helper_result.max_height,
        vein_settings_min_height=foliage_level_1_2_helper_result.min_height,
        vein_settings_vein_clearance=foliage_level_1_2_helper_result.vein_clearance,
        vein_settings_gab_height=foliage_level_1_2_helper_result.gap_height,
    )
    foliage_level_1_2_helper_result_1 = _foliage_level_1_2_helper(
        primary_params_spacing=foliage_level_1_2_helper_result.next_level_spacing,
        primary_params_max_thickness=0.01,
        other_params_min_thickness_scale=0.0,
        other_params_max_height_scale=0.05,
        other_params_min_height_scale=0.0,
        other_params_clearance_scale=0.399517,
        other_params_gab_height_scale=0.0005,
        other_params_next_level_scale=0.4,
    )
    vein_level_2_cell_result = _vein_level_2_cell(
        vector=vein_level_1_parallel_result.vector,
        base_cell_id=vein_level_1_parallel_result.cell_id,
        base_mask=vein_level_1_parallel_result.mask,
        base_clearance=vein_level_1_parallel_result.clearance,
        base_height=vein_level_1_parallel_result.height,
        vein_settings_spacing=foliage_level_1_2_helper_result_1.spacing,
        vein_settings_max_thickness=foliage_level_1_2_helper_result_1.max_thickness,
        vein_settings_min_thickness=foliage_level_1_2_helper_result_1.min_thickness,
        vein_settings_max_height=foliage_level_1_2_helper_result_1.max_height,
        vein_settings_min_height=foliage_level_1_2_helper_result_1.min_height,
        vein_settings_vein_clearance=foliage_level_1_2_helper_result_1.vein_clearance,
        vein_settings_gab_height=foliage_level_1_2_helper_result_1.gap_height,
    )
    foliage_level_1_2_helper_result_2 = _foliage_level_1_2_helper(
        primary_params_spacing=foliage_level_1_2_helper_result_1.next_level_spacing,
        primary_params_max_thickness=0.01,
        other_params_min_thickness_scale=0.0,
        other_params_max_height_scale=0.05,
        other_params_min_height_scale=0.0,
        other_params_clearance_scale=0.399517,
        other_params_gab_height_scale=0.0,
        other_params_next_level_scale=0.4,
    )
    vein_level_2_cell_result_1 = _vein_level_2_cell(
        vector=vein_level_2_cell_result.vector,
        base_cell_id=vein_level_2_cell_result.cell_id,
        base_mask=vein_level_2_cell_result.mask,
        base_clearance=vein_level_2_cell_result.clearance,
        base_height=vein_level_2_cell_result.height,
        vein_settings_spacing=foliage_level_1_2_helper_result_2.spacing,
        vein_settings_max_thickness=foliage_level_1_2_helper_result_2.max_thickness,
        vein_settings_min_thickness=foliage_level_1_2_helper_result_2.min_thickness,
        vein_settings_max_height=foliage_level_1_2_helper_result_2.max_height,
        vein_settings_min_height=foliage_level_1_2_helper_result_2.min_height,
        vein_settings_vein_clearance=foliage_level_1_2_helper_result_2.vein_clearance,
        vein_settings_gab_height=foliage_level_1_2_helper_result_2.gap_height,
        vein_settings_alpha=0.525,
        distortion_size=0.09,
    )
    foliage_level_1_2_helper_result_3 = _foliage_level_1_2_helper(
        primary_params_spacing=foliage_level_1_2_helper_result_2.next_level_spacing,
        primary_params_max_thickness=0.01,
        other_params_min_thickness_scale=0.0,
        other_params_max_height_scale=0.05,
        other_params_min_height_scale=0.0,
        other_params_clearance_scale=0.399517,
        other_params_gab_height_scale=0.0,
        other_params_next_level_scale=0.4,
    )
    vein_level_2_cell_result_2 = _vein_level_2_cell(
        vector=vein_level_2_cell_result_1.vector,
        base_cell_id=vein_level_2_cell_result_1.cell_id,
        base_mask=vein_level_2_cell_result_1.mask,
        base_clearance=vein_level_2_cell_result_1.clearance,
        base_height=vein_level_2_cell_result_1.height,
        vein_settings_spacing=foliage_level_1_2_helper_result_3.spacing,
        vein_settings_max_thickness=foliage_level_1_2_helper_result_3.max_thickness,
        vein_settings_min_thickness=foliage_level_1_2_helper_result_3.min_thickness,
        vein_settings_max_height=foliage_level_1_2_helper_result_3.max_height,
        vein_settings_min_height=foliage_level_1_2_helper_result_3.min_height,
        vein_settings_vein_clearance=foliage_level_1_2_helper_result_3.vein_clearance,
        vein_settings_gab_height=foliage_level_1_2_helper_result_3.gap_height,
        vein_settings_alpha=0.45,
        distortion_size=0.03,
        distortion_strength=0.5,
    )
    color_offset_base_color = pf.color.hsv_color((0.316, 0.8559, 0.1349))
    color_offset_result = _color_offset(
        base_color=color_offset_base_color, hue_offset=-0.05, value=1.3
    )
    color_offset_result_1 = _color_offset(
        base_color=color_offset_result.offset_color,
        hue_offset=-0.05,
        saturation=0.8,
        value=2.0,
    )
    leaf_shader_result = _leaf_shader(
        mask=vein_level_2_cell_result_2.mask,
        clearance=vein_level_2_cell_result_2.clearance,
        leaf_color_1=color_offset_result.base_color,
        leaf_color_2=color_offset_result_1.base_color,
        vein_color=color_offset_result_1.offset_color,
    )
    displacement = pf.nodes.shader.displacement(
        height=vein_level_2_cell_result_2.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=leaf_shader_result, displacement=displacement, volume=None
    )


def leaf_ridged_preset(vector: t.SocketOrVal[pf.Vector]) -> pf.Material:
    # Code generated by procfunc v0.30.1
    vein_level_0_result = _vein_level_0(vector=vector, max_thickness=0.01)
    vein_level_1_parallel_result = _vein_level_1_parallel(
        vector=vein_level_0_result.vector,
        base_cell_id=vein_level_0_result.cell_id,
        base_mask=vein_level_0_result.mask,
        base_clearance=vein_level_0_result.clearance,
        vein_settings_rotation=0.118682,
        vein_settings_spacing=0.015,
        vein_settings_randomness=1.0,
        vein_settings_shear=0.2,
        vein_settings_max_thickness=0.1,
        vein_settings_min_thickness=0.005,
        vein_settings_vein_clearance=0.402258,
        vein_settings_gab_height=-0.0025,
        distortion_strength=0.01,
    )
    surface_leaf_color_1 = pf.color.hsv_color((0.3155, 0.841, 0.0796))
    surface_leaf_color_0 = pf.color.hsv_color((0.2966, 0.8799, 0.1293))
    surface_vein_color = pf.color.hsv_color((0.293, 0.8612, 0.1862))
    leaf_shader_result = _leaf_shader(
        mask=vein_level_1_parallel_result.mask,
        clearance=vein_level_1_parallel_result.clearance,
        leaf_color_1=surface_leaf_color_1,
        leaf_color_2=surface_leaf_color_0,
        vein_color=surface_vein_color,
    )
    displacement = pf.nodes.shader.displacement(
        height=vein_level_1_parallel_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=leaf_shader_result, displacement=displacement, volume=None
    )


def leaf_rounded_sections_preset(vector: t.SocketOrVal[pf.Vector]) -> pf.Material:
    # Code generated by procfunc v0.30.1
    vein_level_0_result = _vein_level_0(
        vector=vector, max_thickness=0.01, vein_clearance=0.3, gab_height=0.001
    )
    vein_level_1_parallel_result = _vein_level_1_parallel(
        vector=vein_level_0_result.vector,
        base_cell_id=vein_level_0_result.cell_id,
        base_mask=vein_level_0_result.mask,
        base_clearance=vein_level_0_result.clearance,
        base_height=vein_level_0_result.height,
        vein_settings_rotation=0.453786,
        vein_settings_randomness=0.877419,
        vein_settings_left_offset=4.4,
        vein_settings_shear=0.05,
        vein_settings_max_thickness=0.04,
        vein_settings_min_thickness=0.005,
        vein_settings_vein_clearance=0.402258,
        vein_settings_gab_height=0.001,
        distortion_strength=0.2,
    )
    vein_level_2_cell_result = _vein_level_2_cell(
        vector=vein_level_1_parallel_result.vector,
        base_cell_id=vein_level_1_parallel_result.cell_id,
        base_mask=vein_level_1_parallel_result.mask,
        base_clearance=vein_level_1_parallel_result.clearance,
        base_height=vein_level_1_parallel_result.height,
        vein_settings_max_thickness=0.03,
        vein_settings_max_height=0.0001,
        vein_settings_vein_clearance=0.0002,
        vein_settings_sharpness=0.0,
        vein_settings_alpha=0.509677,
    )
    vein_level_2_cell_result_1 = _vein_level_2_cell(
        vector=vein_level_2_cell_result.vector,
        base_cell_id=vein_level_2_cell_result.cell_id,
        base_mask=vein_level_2_cell_result.mask,
        base_clearance=vein_level_2_cell_result.clearance,
        base_height=vein_level_2_cell_result.height,
        vein_settings_spacing=0.03,
        vein_settings_max_thickness=0.03,
        vein_settings_max_height=0.0001,
        vein_settings_vein_clearance=0.0002,
        vein_settings_sharpness=0.0,
        vein_settings_alpha=0.509677,
    )
    vein_level_2_cell_result_2 = _vein_level_2_cell(
        vector=vein_level_2_cell_result_1.vector,
        base_cell_id=vein_level_2_cell_result_1.cell_id,
        base_mask=vein_level_2_cell_result_1.mask,
        base_clearance=vein_level_2_cell_result_1.clearance,
        base_height=vein_level_2_cell_result_1.height,
        vein_settings_spacing=0.015,
        vein_settings_max_thickness=0.05,
        vein_settings_max_height=0.0001,
        vein_settings_vein_clearance=0.0002,
        vein_settings_sharpness=0.0,
        vein_settings_alpha=0.509677,
    )
    surface_leaf_color_1 = pf.color.hsv_color((0.2795, 0.9092, 0.2195))
    surface_leaf_color_0 = pf.color.hsv_color((0.2795, 0.9092, 0.2195))
    surface_vein_color = pf.color.hsv_color((0.2417, 0.7917, 0.3265))
    leaf_shader_result = _leaf_shader(
        mask=vein_level_2_cell_result_2.mask,
        clearance=vein_level_2_cell_result_2.clearance,
        leaf_color_1=surface_leaf_color_1,
        leaf_color_2=surface_leaf_color_0,
        vein_color=surface_vein_color,
        roughness=0.482576,
        specular_ior_level=0.775,
    )
    displacement = pf.nodes.shader.displacement(
        height=vein_level_2_cell_result_2.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=leaf_shader_result, displacement=displacement, volume=None
    )


def leaf_streaks_preset(vector: t.SocketOrVal[pf.Vector]) -> pf.Material:
    # Code generated by procfunc v0.30.1
    vein_level_0_result = _vein_level_0(
        vector=vector,
        max_thickness=0.022,
        max_height=0.0002,
        min_height=0.0,
        vein_clearance=0.5,
        gab_height=0.001,
        sharpness=1.0,
    )
    color_offset_base_color = pf.color.hsv_color((0.3366, 0.9283, 0.1678))
    color_offset_result = _color_offset(
        base_color=color_offset_base_color, hue_offset=-0.05, value=1.3
    )
    leaf_growth_streaks_result = _leaf_growth_streaks(
        vector=vector,
        color_1=color_offset_result.base_color,
        color_2=color_offset_result.offset_color,
        height=0.0001,
        distortion_size=0.3,
        distortion_detail=6.0,
    )
    color_offset_result_1 = _color_offset(
        base_color=color_offset_result.base_color, value=0.6
    )
    leaf_shader_result = _leaf_shader(
        mask=vein_level_0_result.mask,
        clearance=vein_level_0_result.clearance,
        leaf_color_1=leaf_growth_streaks_result.color,
        leaf_color_2=color_offset_result_1.offset_color,
        vein_color=color_offset_result_1.offset_color,
        roughness=0.349242,
        specular_ior_level=0.508333,
    )
    displacement = pf.nodes.shader.displacement(
        height=vein_level_0_result.height + leaf_growth_streaks_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=leaf_shader_result, displacement=displacement, volume=None
    )


def leaf_velvet_preset(vector: t.SocketOrVal[pf.Vector]) -> pf.Material:
    # Code generated by procfunc v0.30.1
    vein_level_0_result = _vein_level_0(
        vector=vector, max_thickness=0.01, vein_clearance=0.3, gab_height=0.0015
    )
    vein_level_1_parallel_result = _vein_level_1_parallel(
        vector=vein_level_0_result.vector,
        base_cell_id=vein_level_0_result.cell_id,
        base_mask=vein_level_0_result.mask,
        base_clearance=vein_level_0_result.clearance,
        vein_settings_rotation=0.453786,
        vein_settings_spacing=0.08,
        vein_settings_randomness=0.625806,
        vein_settings_shear=0.05,
        vein_settings_max_thickness=0.04,
        vein_settings_min_thickness=0.005,
        vein_settings_vein_clearance=0.402258,
        vein_settings_gab_height=0.0005,
        distortion_size=1.3,
        distortion_strength=0.2,
        distortion_detail=4.0,
    )
    surface_leaf_color_1 = pf.color.hsv_color((0.2707, 0.8354, 0.38))
    surface_leaf_color_0 = pf.color.hsv_color((0.2931, 0.8745, 0.38))
    surface_sheen_tint = pf.color.hsv_color((0.224, 0.8634, 1.0))
    leaf_shader_result = _leaf_shader(
        mask=vein_level_1_parallel_result.mask,
        clearance=vein_level_1_parallel_result.clearance,
        leaf_color_1=surface_leaf_color_1,
        leaf_color_2=surface_leaf_color_0,
        roughness=0.774242,
        specular_ior_level=0.108333,
        sheen_weight=1.0,
        sheen_tint=surface_sheen_tint,
    )
    displacement = pf.nodes.shader.displacement(
        height=vein_level_1_parallel_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=leaf_shader_result, displacement=displacement, volume=None
    )


def leaf(
    vector: t.SocketOrVal[pf.Vector],
    color: t.SocketOrVal[pf.Color],
    light_color: t.SocketOrVal[pf.Color],
    vein_color: t.SocketOrVal[pf.Color],
    level_0_max_thickness: t.SocketOrVal[float],
    level_0_vein_clearance: t.SocketOrVal[float],
    vein_spacing: t.SocketOrVal[float],
    vein_shear: t.SocketOrVal[float],
    vein_max_thickness: t.SocketOrVal[float],
    vein_gap_height: t.SocketOrVal[float],
    distortion_strength: t.SocketOrVal[float],
    roughness: t.SocketOrVal[float],
    specular_ior_level: t.SocketOrVal[float],
    translucency: t.SocketOrVal[float],
    sheen_weight: t.SocketOrVal[float],
) -> pf.Material:
    vein_level_0_result = _vein_level_0(
        vector=vector,
        max_thickness=level_0_max_thickness,
        vein_clearance=level_0_vein_clearance,
    )
    vein_level_1_parallel_result = _vein_level_1_parallel(
        vector=vein_level_0_result.vector,
        base_cell_id=vein_level_0_result.cell_id,
        base_mask=vein_level_0_result.mask,
        base_clearance=vein_level_0_result.clearance,
        base_height=vein_level_0_result.height,
        vein_settings_spacing=vein_spacing,
        vein_settings_randomness=1.0,
        vein_settings_shear=vein_shear,
        vein_settings_max_thickness=vein_max_thickness,
        vein_settings_min_thickness=0.005,
        vein_settings_vein_clearance=0.402258,
        vein_settings_gab_height=vein_gap_height,
        distortion_strength=distortion_strength,
    )
    leaf_shader_result = _leaf_shader(
        mask=vein_level_1_parallel_result.mask,
        clearance=vein_level_1_parallel_result.clearance,
        leaf_color_1=color,
        leaf_color_2=light_color,
        vein_color=vein_color,
        roughness=roughness,
        specular_ior_level=specular_ior_level,
        translucency=translucency,
        sheen_weight=sheen_weight,
    )
    displacement = pf.nodes.shader.displacement(
        height=vein_level_1_parallel_result.height,
        midlevel=0.0,
        normal=(0.0, 0.0, 0.0),
    )
    return pf.Material(
        surface=leaf_shader_result, displacement=displacement, volume=None
    )


@pf.tracer.grammar
def leaf_color_rand(rng: pf.RNG) -> t.SocketOrVal[pf.Color]:
    saturation = pf.random.clip_gaussian(rng, 0.8, 0.3, 0.25, 0.97)
    hue = pf.random.clip_gaussian(rng, 0.29, 0.06, 0.18, 0.39)
    value = pf.random.clip_gaussian(rng, 0.11, 0.25, 0.05, 0.6)
    value = value * (1.1 - 0.35 * saturation)
    return pf.color.hsv_color(hue=hue, saturation=saturation, value=value)


@pf.tracer.grammar
def leaf_rand(
    rng: pf.RNG,
    vector: t.SocketOrVal[pf.Vector],
    color: t.SocketOrVal[pf.Color] | None = None,
) -> pf.Material:
    rng_color, rng = rng.spawn(2)
    if color is None:
        color = leaf_color_rand(rng_color)

    light_hue = pf.random.uniform(rng, 0.48, 0.52)
    light_saturation = pf.random.uniform(rng, 0.85, 1.0)
    light_value = pf.random.uniform(rng, 1.15, 1.65)
    light_color = pf.nodes.color.hue_saturation(
        color,
        fac=1.0,
        hue=light_hue,
        saturation=light_saturation,
        value=light_value,
    )
    vein_hue = pf.random.uniform(rng, 0.47, 0.52)
    vein_saturation = pf.random.uniform(rng, 0.8, 1.0)
    vein_value = pf.random.uniform(rng, 1.4, 2.4)
    vein_color = pf.nodes.color.hue_saturation(
        color,
        fac=1.0,
        hue=vein_hue,
        saturation=vein_saturation,
        value=vein_value,
    )
    level_0_max_thickness = pf.random.uniform(rng, 0.01, 0.022)
    level_0_vein_clearance = pf.random.uniform(rng, 0.2, 0.5)
    vein_spacing = pf.random.uniform(rng, 0.015, 0.1)
    vein_shear = pf.random.uniform(rng, 0.0, 0.2)
    vein_max_thickness = pf.random.uniform(rng, 0.04, 0.1)
    vein_gap_height = pf.random.uniform(rng, -0.0025, 0.001)
    distortion_strength = pf.random.uniform(rng, 0.01, 0.2)
    roughness = pf.random.uniform(rng, 0.349242, 0.774242)
    specular_ior_level = pf.random.uniform(rng, 0.108333, 1.0)
    translucency = pf.random.uniform(rng, 0.05, 0.2)
    sheen_weight = pf.random.uniform(rng, 0.0, 1.0)
    return leaf(
        vector=vector,
        color=color,
        light_color=light_color,
        vein_color=vein_color,
        level_0_max_thickness=level_0_max_thickness,
        level_0_vein_clearance=level_0_vein_clearance,
        vein_spacing=vein_spacing,
        vein_shear=vein_shear,
        vein_max_thickness=vein_max_thickness,
        vein_gap_height=vein_gap_height,
        distortion_strength=distortion_strength,
        roughness=roughness,
        specular_ior_level=specular_ior_level,
        translucency=translucency,
        sheen_weight=sheen_weight,
    )
